import 'dart:math';

import 'package:monte/core/domain/engine/card.dart';
import 'package:monte/core/domain/engine/game.dart';
import 'package:monte/core/domain/engine/hand_evaluator.dart';
import 'package:monte/core/domain/engine/player.dart';

/// A rough estimate of a player's hand strength in [0, 1], shared by the
/// heuristic and personality policies so they agree on "how good is this hand".
///
/// Preflop reads a baked per-hand table (see below); postflop maps the made-hand
/// category (nudged by the top kicker) onto the same scale.
class HandStrength {
  const HandStrength._();

  static double estimate(PokerGame game, Player p) {
    if (game.board.isEmpty) return preflop(p);

    final value = HandEvaluator.evaluate([...p.hole, ...game.board]);
    final base = value.rank.index / (HandRank.values.length - 1);
    final kicker = value.tiebreakers.first / 14.0 * 0.05;
    return (base * 0.9 + kicker + 0.05).clamp(0.0, 1.0);
  }

  static double preflop(Player p) => preflopOf(p.hole[0], p.hole[1]);

  /// Preflop strength for any two cards, independent of a [Player] — used both
  /// by [preflop] and by range calibration that enumerates all starting hands.
  ///
  /// Values are a **baked table** (`tool/gen_preflop_table.dart`): the real
  /// [HandEvaluator] Monte-Carlos each of the 169 canonical hands' heads-up
  /// all-in equity vs a random hand, then those equities are histogram-matched
  /// onto the previous smooth-formula distribution. Net effect: the *ordering*
  /// now reflects true equity (no KJs<KTs-style inversions, no plateaus), while
  /// the output *distribution* is unchanged — so the policies' absolute
  /// thresholds and [PreflopRanges]' percentile cutoffs keep their meaning.
  static double preflopOf(Card x, Card y) {
    final high = max(x.rank.value, y.rank.value);
    final low = min(x.rank.value, y.rank.value);
    final suited = high != low && x.suit == y.suit;
    // Table is complete over ranks 2..14, so the lookup always hits.
    return _table[high * 100 + low * 2 + (suited ? 1 : 0)]!;
  }

  /// Baked preflop strengths keyed by `high*100 + low*2 + (suited ? 1 : 0)`
  /// (ranks 2..14, ace = 14). Generated by `tool/gen_preflop_table.dart` — do
  /// not hand-edit; regenerate to change.
  static const Map<int, double> _table = {
    204: 0.3887, // 22
    304: 0.1286, // 32o
    305: 0.1929, // 32s
    306: 0.4443, // 33
    404: 0.1500, // 42o
    405: 0.2143, // 42s
    406: 0.1929, // 43o
    407: 0.2371, // 43s
    408: 0.4930, // 44
    504: 0.1571, // 52o
    505: 0.2143, // 52s
    506: 0.2043, // 53o
    507: 0.2571, // 53s
    508: 0.2357, // 54o
    509: 0.2793, // 54s
    510: 0.5504, // 55
    604: 0.1714, // 62o
    605: 0.2357, // 62s
    606: 0.1952, // 63o
    607: 0.2571, // 63s
    608: 0.2357, // 64o
    609: 0.2786, // 64s
    610: 0.2650, // 65o
    611: 0.3000, // 65s
    612: 0.6229, // 66
    704: 0.1714, // 72o
    705: 0.2357, // 72s
    706: 0.2143, // 73o
    707: 0.2571, // 73s
    708: 0.2429, // 74o
    709: 0.2943, // 74s
    710: 0.2786, // 75o
    711: 0.3157, // 75s
    712: 0.3000, // 76o
    713: 0.3286, // 76s
    714: 0.6875, // 77
    804: 0.2143, // 82o
    805: 0.2729, // 82s
    806: 0.2300, // 83o
    807: 0.2786, // 83s
    808: 0.2514, // 84o
    809: 0.3000, // 84s
    810: 0.2786, // 85o
    811: 0.3186, // 85s
    812: 0.3000, // 86o
    813: 0.3429, // 86s
    814: 0.3229, // 87o
    815: 0.3650, // 87s
    816: 0.7519, // 88
    904: 0.2571, // 92o
    905: 0.3000, // 92s
    906: 0.2571, // 93o
    907: 0.3000, // 93s
    908: 0.2786, // 94o
    909: 0.3157, // 94s
    910: 0.3000, // 95o
    911: 0.3329, // 95s
    912: 0.3214, // 96o
    913: 0.3429, // 96s
    914: 0.3371, // 97o
    915: 0.3800, // 97s
    916: 0.3643, // 98o
    917: 0.4014, // 98s
    918: 0.7625, // 99
    1004: 0.2829, // T2o
    1005: 0.3214, // T2s
    1006: 0.2943, // T3o
    1007: 0.3371, // T3s
    1008: 0.3079, // T4o
    1009: 0.3429, // T4s
    1010: 0.3214, // T5o
    1011: 0.3429, // T5s
    1012: 0.3429, // T6o
    1013: 0.3657, // T6s
    1014: 0.3586, // T7o
    1015: 0.3950, // T7s
    1016: 0.3800, // T8o
    1017: 0.4207, // T8s
    1018: 0.4100, // T9o
    1019: 0.4321, // T9s
    1020: 0.8000, // TT
    1104: 0.3214, // J2o
    1105: 0.3429, // J2s
    1106: 0.3214, // J3o
    1107: 0.3643, // J3s
    1108: 0.3429, // J4o
    1109: 0.3800, // J4s
    1110: 0.3429, // J5o
    1111: 0.3857, // J5s
    1112: 0.3643, // J6o
    1113: 0.3917, // J6s
    1114: 0.3857, // J7o
    1115: 0.4229, // J7s
    1116: 0.4071, // J8o
    1117: 0.4443, // J8s
    1118: 0.4286, // J9o
    1119: 0.4571, // J9s
    1120: 0.4514, // JTo
    1121: 0.4900, // JTs
    1122: 0.8375, // JJ
    1204: 0.3586, // Q2o
    1205: 0.3800, // Q2s
    1206: 0.3643, // Q3o
    1207: 0.4071, // Q3s
    1208: 0.3714, // Q4o
    1209: 0.4143, // Q4s
    1210: 0.3857, // Q5o
    1211: 0.4229, // Q5s
    1212: 0.4014, // Q6o
    1213: 0.4286, // Q6s
    1214: 0.4029, // Q7o
    1215: 0.4471, // Q7s
    1216: 0.4286, // Q8o
    1217: 0.4657, // Q8s
    1218: 0.4657, // Q9o
    1219: 0.5086, // Q9s
    1220: 0.4871, // QTo
    1221: 0.5300, // QTs
    1222: 0.5114, // QJo
    1223: 0.5450, // QJs
    1224: 0.8750, // QQ
    1304: 0.3857, // K2o
    1305: 0.4229, // K2s
    1306: 0.4071, // K3o
    1307: 0.4443, // K3s
    1308: 0.4143, // K4o
    1309: 0.4500, // K4s
    1310: 0.4243, // K5o
    1311: 0.4657, // K5s
    1312: 0.4379, // K6o
    1313: 0.4829, // K6s
    1314: 0.4500, // K7o
    1315: 0.5000, // K7s
    1316: 0.4714, // K8o
    1317: 0.5150, // K8s
    1318: 0.5017, // K9o
    1319: 0.5514, // K9s
    1320: 0.5393, // KTo
    1321: 0.5857, // KTs
    1322: 0.5729, // KJo
    1323: 0.5979, // KJs
    1324: 0.5814, // KQo
    1325: 0.6057, // KQs
    1326: 0.9125, // KK
    1404: 0.4571, // A2o
    1405: 0.4986, // A2s
    1406: 0.4714, // A3o
    1407: 0.5157, // A3s
    1408: 0.4757, // A4o
    1409: 0.5300, // A4s
    1410: 0.5000, // A5o
    1411: 0.5371, // A5s
    1412: 0.4943, // A6o
    1413: 0.5371, // A6s
    1414: 0.5214, // A7o
    1415: 0.5780, // A7s
    1416: 0.5429, // A8o
    1417: 0.5857, // A8s
    1418: 0.5614, // A9o
    1419: 0.6029, // A9s
    1420: 0.5879, // ATo
    1421: 0.6657, // ATs
    1422: 0.6107, // AJo
    1423: 0.6829, // AJs
    1424: 0.6466, // AQo
    1425: 0.6871, // AQs
    1426: 0.6721, // AKo
    1427: 0.7188, // AKs
    1428: 0.9500, // AA
  };
}
