// GENERATED — do not edit by hand.
//
// Regenerated by tool/create_player.dart whenever a player is created. Holds the
// owner-authored players, spread into homeGameProfiles / builtInProfiles.
import 'package:monte/core/domain/ai/player_profile.dart';

/// Owner-created recreational players (appended to the home-game roster).
final List<PlayerProfile> customRecreationalPlayers = <PlayerProfile>[
];

/// Owner-created pros (appended to the built-in pro roster).
final List<PlayerProfile> customPros = <PlayerProfile>[
];
