import 'package:monte/core/domain/ai/player_profile.dart';

/// A curated pack of well-known pros, each approximated along the profile axes:
/// preflop frequencies (VPIP/PFR/3-bet), the GTO↔exploit lean, bet sizing
/// (`risk`), and signature-move characteristics (soul read, geometric overbet,
/// positional warfare, leverage pressure). These are *style approximations* from
/// each player's reputation, not exact clones — and every one is calibrator-
/// feasible (a real open range, a VPIP>PFR gap, 3-bet ≤ 0.14). Spread into
/// `builtInProfiles`, so they appear in the tournament lobby and play their style.

PlayerCharacteristic _soul(double p) =>
    PlayerCharacteristic(id: 'Soul_Read', proficiency: p);
PlayerCharacteristic _geo(double p) =>
    PlayerCharacteristic(id: 'Geometric_Overbet_Execution', proficiency: p);
PlayerCharacteristic _pos(double p) =>
    PlayerCharacteristic(id: 'Positional_Warfare', proficiency: p);
PlayerCharacteristic _lev(double p) =>
    PlayerCharacteristic(id: 'Leverage_Pressure', proficiency: p);
PlayerCharacteristic _trap(double p) =>
    PlayerCharacteristic(id: 'Slow_Play_Trap', proficiency: p);
PlayerCharacteristic _sticky(double p) =>
    PlayerCharacteristic(id: 'Sticky_Showdown', proficiency: p);
PlayerCharacteristic _float(double p) =>
    PlayerCharacteristic(id: 'Float_And_Take_Away', proficiency: p);
PlayerCharacteristic _bubble(double p) =>
    PlayerCharacteristic(id: 'Bubble_Predator', proficiency: p);
PlayerCharacteristic _limp(double p) =>
    PlayerCharacteristic(id: 'Limp_Reraise', proficiency: p);
PlayerCharacteristic _under(double p) =>
    PlayerCharacteristic(id: 'Underbluff_Exploit', proficiency: p);
PlayerCharacteristic _cr(double p) =>
    PlayerCharacteristic(id: 'Check_Raise_Merchant', proficiency: p);
PlayerCharacteristic _blowup(double p) =>
    PlayerCharacteristic(id: 'Tilt_Blowup', proficiency: p);
PlayerCharacteristic _chase(double p) =>
    PlayerCharacteristic(id: 'Tilt_Chase', proficiency: p);
PlayerCharacteristic _shutdown(double p) =>
    PlayerCharacteristic(id: 'Tilt_Shutdown', proficiency: p);

PlayerProfile _p(
  String id,
  String name,
  String archetype, {
  required double vpip,
  required double pfr,
  required double threeBet,
  required double gto,
  double exploit = 0.3,
  double risk = 1.0,
  double tilt = 0.92,
  double oppRead = 0.6,
  List<PlayerCharacteristic> chars = const [],
  required String desc,
}) =>
    PlayerProfile(
      id: id,
      name: name,
      archetype: archetype,
      skill: 1.0,
      strategicBaseline: StrategicBaseline(
        vpipTarget: vpip,
        pfrTarget: pfr,
        threeBetFrequency: threeBet,
        gtoAdherenceWeight: gto,
      ),
      behavioralModifiers: BehavioralModifiers(
        tiltResistance: tilt,
        exploitativeWeight: exploit,
        riskPremiumCoefficient: risk,
        weightOnOpponentHistory: oppRead,
      ),
      generalTraits: const GeneralTraits(
        positionAwareness: 0.9,
        potOdds: 0.9,
        impliedOdds: 0.85,
      ),
      characteristics: chars,
      description: desc,
    );

/// The famous-pro roster (spread into `builtInProfiles`).
final List<PlayerProfile> famousPros = [
  // ---- Modern / solver-era GTO aggressors ---------------------------------
  _p('FP001', 'Stephen Chidwick', 'GTO_Technician',
      vpip: 0.25, pfr: 0.19, threeBet: 0.11, gto: 0.95, exploit: 0.12,
      chars: [_geo(0.6), _pos(0.7), _cr(0.6)],
      desc: 'Studious, near-unexploitable high-stakes technician.'),
  _p('FP002', 'Fedor Holz', 'GTO_Wunderkind',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.93, exploit: 0.25, risk: 1.15,
      chars: [_geo(0.7), _pos(0.7), _lev(0.5), _bubble(0.75), _cr(0.6)],
      desc: 'Aggressive, disciplined solver-era great.'),
  _p('FP003', 'Justin Bonomo', 'GTO_High_Roller',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.93, exploit: 0.25, risk: 1.15,
      chars: [_geo(0.7), _pos(0.7)],
      desc: 'Balanced GTO crusher across every format.'),
  _p('FP004', 'Jason Koon', 'GTO_High_Roller',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.93, exploit: 0.25, risk: 1.15,
      chars: [_geo(0.7), _pos(0.7)],
      desc: "An athlete's discipline applied to top-tier GTO."),
  _p('FP005', 'Adrian Mateos', 'GTO_Aggressor',
      vpip: 0.27, pfr: 0.21, threeBet: 0.12, gto: 0.9, exploit: 0.3, risk: 1.2,
      chars: [_pos(0.8), _lev(0.5), _geo(0.6), _bubble(0.75)],
      desc: 'Precise, aggressive European GTO star.'),
  _p('FP006', 'Bryn Kenney', 'Fearless_High_Roller',
      vpip: 0.29, pfr: 0.22, threeBet: 0.13, gto: 0.88, exploit: 0.35, risk: 1.35,
      chars: [_lev(0.8), _geo(0.7), _pos(0.6), _bubble(0.8)],
      desc: 'Fearless high-roller; relentless aggression and big sizing.'),
  _p('FP007', 'Koray Aldemir', 'Measured_Aggressor',
      vpip: 0.25, pfr: 0.19, threeBet: 0.10, gto: 0.9, exploit: 0.25,
      chars: [_pos(0.7), _geo(0.5)],
      desc: 'Measured, aggressive world champion.'),
  _p('FP008', 'Scott Seiver', 'Adaptive_Reg',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.85, exploit: 0.35, risk: 1.15,
      chars: [_soul(0.6), _geo(0.6), _pos(0.6), _cr(0.65)],
      desc: 'Sharp, adaptive, endlessly tough high-stakes reg.'),
  _p('FP009', 'Dario Sammartino', 'Creative_Aggressor',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.85, exploit: 0.35, risk: 1.2,
      chars: [_lev(0.6), _geo(0.6), _float(0.6), _cr(0.7)],
      desc: 'Creative, aggressive Italian high-roller.'),
  _p('FP010', 'Brian Rast', 'Versatile_Pro',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.85, exploit: 0.35,
      chars: [_soul(0.6), _pos(0.6)],
      desc: 'Versatile and tough across every format.'),
  _p('FP011', 'Doug Polk', 'Heads_Up_Assassin',
      vpip: 0.30, pfr: 0.23, threeBet: 0.13, gto: 0.9, exploit: 0.4, risk: 1.3,
      chars: [_lev(0.8), _geo(0.7), _pos(0.6), _float(0.8), _cr(0.75)],
      desc: 'Ruthless heads-up specialist; maximum pressure.'),
  _p('FP012', 'Phil Galfond', 'Deep_Thinker',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.9, exploit: 0.3, risk: 1.1,
      chars: [_geo(0.7), _pos(0.6), _cr(0.7)],
      desc: 'Deep-thinking PLO/NLHE great.'),
  _p('FP013', 'Nick Schulman', 'Sharp_Mixed',
      vpip: 0.25, pfr: 0.19, threeBet: 0.10, gto: 0.87, exploit: 0.35,
      chars: [_soul(0.6)],
      desc: 'Sharp mixed-game player and reader.'),
  _p('FP014', 'Benny Glaser', 'Mixed_Technician',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.9, exploit: 0.2,
      chars: [_pos(0.6)],
      desc: 'Mixed-game technician; disciplined.'),
  _p('FP015', 'Paul Sokolov', 'Modern_Reg',
      vpip: 0.28, pfr: 0.21, threeBet: 0.11, gto: 0.85, exploit: 0.3, risk: 1.1,
      chars: [_lev(0.5), _pos(0.6)],
      desc: 'Aggressive modern online-bred reg.'),

  // ---- Aggressive tournament crushers -------------------------------------
  _p('FP016', 'Michael Mizrachi', 'Aggressive_Grinder',
      vpip: 0.30, pfr: 0.23, threeBet: 0.13, gto: 0.8, exploit: 0.45, risk: 1.3,
      chars: [_lev(0.7), _geo(0.6), _cr(0.6)],
      desc: 'The Grinder — aggressive and fearless.'),
  _p('FP017', 'Ben Lamb', 'Aggressive_MTT',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.82, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.6), _geo(0.5), _bubble(0.8), _cr(0.6)],
      desc: 'Aggressive tournament crusher.'),
  _p('FP018', 'Greg Merson', 'Disciplined_Aggressor',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.85, exploit: 0.3,
      chars: [_pos(0.6)],
      desc: 'Disciplined WSOP Main Event champion.'),
  _p('FP019', 'Ryan Riess', 'Young_Aggressor',
      vpip: 0.28, pfr: 0.21, threeBet: 0.11, gto: 0.8, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.6)],
      desc: 'Aggressive young champion.'),
  _p('FP020', 'Joe Cada', 'Aggressive_Champion',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.85, exploit: 0.35, risk: 1.15,
      chars: [_pos(0.6), _lev(0.5)],
      desc: 'Aggressive multi-bracelet winner.'),
  _p('FP021', 'Jonathan Duhamel', 'Aggressive_Champion',
      vpip: 0.28, pfr: 0.21, threeBet: 0.11, gto: 0.82, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.6)],
      desc: 'Aggressive Canadian champion.'),
  _p('FP022', 'Peter Eastgate', 'Calm_Solid',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.85, exploit: 0.3,
      chars: [_pos(0.6)],
      desc: 'Calm, solid Main Event champion.'),
  _p('FP023', 'John Racener', 'Steady_Pro',
      vpip: 0.25, pfr: 0.19, threeBet: 0.10, gto: 0.85, exploit: 0.3,
      desc: 'Steady, solid tournament pro.'),
  _p('FP024', 'Paul Wasicka', 'Composed_Pro',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.85, exploit: 0.3,
      desc: 'Composed final-table pro.'),
  _p('FP025', 'Joe Hachem', 'Personable_Aggressor',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.8, exploit: 0.35, risk: 1.1,
      chars: [_lev(0.5)],
      desc: 'Aggressive, personable champion.'),
  _p('FP026', 'Carlos Mortensen', 'The_Matador',
      vpip: 0.30, pfr: 0.22, threeBet: 0.12, gto: 0.78, exploit: 0.45, risk: 1.25,
      chars: [_lev(0.6), _soul(0.5), _limp(0.5)],
      desc: 'The Matador — aggressive and fearless.'),
  _p('FP027', 'Maurice Hawkins', 'High_Volume_Grinder',
      vpip: 0.30, pfr: 0.22, threeBet: 0.12, gto: 0.78, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.6), _bubble(0.7)],
      desc: 'High-volume, aggressive ring-game grinder.'),
  _p('FP028', 'Josh Arieh', 'Talkative_Aggressor',
      vpip: 0.30, pfr: 0.22, threeBet: 0.12, gto: 0.78, exploit: 0.45, risk: 1.2,
      chars: [_lev(0.6), _soul(0.5), _blowup(0.6)],
      desc: 'Aggressive, talkative live pro.'),
  _p('FP029', 'David Williams', 'Versatile_Aggressor',
      vpip: 0.28, pfr: 0.21, threeBet: 0.11, gto: 0.82, exploit: 0.35, risk: 1.15,
      chars: [_lev(0.5)],
      desc: 'Versatile, aggressive pro.'),
  _p('FP030', 'Ram Vaswani', 'Hendon_Aggressor',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.8, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.6)],
      desc: 'Aggressive Hendon Mob mainstay.'),
  _p('FP031', 'Tuan Le', 'Aggressive_Live',
      vpip: 0.30, pfr: 0.22, threeBet: 0.12, gto: 0.75, exploit: 0.5, risk: 1.2,
      chars: [_lev(0.6), _soul(0.5), _cr(0.6)],
      desc: 'Aggressive WPT-era live pro.'),

  // ---- LAG / hyper-aggressive ---------------------------------------------
  _p('FP032', 'Vanessa Selbst', 'Hyper_LAG',
      vpip: 0.33, pfr: 0.25, threeBet: 0.14, gto: 0.82, exploit: 0.5, risk: 1.4,
      chars: [_lev(0.8), _geo(0.7), _float(0.8), _cr(0.85)],
      desc: 'Fearless, hyper-aggressive crusher.'),
  _p('FP033', 'Patrik Antonius', 'Balanced_LAG',
      vpip: 0.31, pfr: 0.23, threeBet: 0.13, gto: 0.85, exploit: 0.4, risk: 1.3,
      chars: [_lev(0.7), _geo(0.7), _float(0.65), _cr(0.75)],
      desc: 'Balanced, aggressive high-stakes force.'),
  _p('FP034', 'David Benyamine', 'Cash_LAG',
      vpip: 0.32, pfr: 0.24, threeBet: 0.13, gto: 0.75, exploit: 0.5, risk: 1.35,
      chars: [_lev(0.7), _geo(0.6), _cr(0.65)],
      desc: 'Loose-aggressive cash-game force.'),
  _p('FP035', 'Bertrand Grospellier', 'ElkY',
      vpip: 0.31, pfr: 0.23, threeBet: 0.13, gto: 0.82, exploit: 0.4, risk: 1.3,
      chars: [_lev(0.7), _pos(0.6)],
      desc: 'ElkY — fast, aggressive, online-bred.'),
  _p('FP036', 'Eli Elezra', 'Action_Gambler',
      vpip: 0.31, pfr: 0.23, threeBet: 0.12, gto: 0.7, exploit: 0.5, risk: 1.3,
      chars: [_lev(0.7), _soul(0.5), _sticky(0.6), _limp(0.5), _chase(0.6)],
      desc: 'Action-loving live gambler.'),
  _p('FP037', 'Qui Nguyen', 'Unpredictable_LAG',
      vpip: 0.34, pfr: 0.25, threeBet: 0.13, gto: 0.68, exploit: 0.55, risk: 1.35,
      tilt: 0.7, chars: [_lev(0.8), _soul(0.5)],
      desc: 'Fearless, unpredictable live LAG.'),
  _p('FP038', 'Mike Matusow', 'The_Mouth',
      vpip: 0.30, pfr: 0.22, threeBet: 0.12, gto: 0.72, exploit: 0.5, risk: 1.25,
      tilt: 0.35, chars: [_lev(0.7), _soul(0.5), _blowup(0.85)],
      desc: 'The Mouth — aggressive and tilt-prone.'),
  _p('FP039', 'Stu Ungar', 'Instinctive_Genius',
      vpip: 0.32, pfr: 0.24, threeBet: 0.13, gto: 0.8, exploit: 0.55, risk: 1.3,
      oppRead: 0.95, chars: [_soul(0.9), _lev(0.7)],
      desc: 'The Kid — the greatest instinctive tournament genius.'),

  // ---- Old-school legends / feel players (reads-driven) --------------------
  _p('FP040', 'Phil Ivey', 'The_GOAT',
      vpip: 0.28, pfr: 0.21, threeBet: 0.11, gto: 0.85, exploit: 0.5, risk: 1.2,
      tilt: 0.99, oppRead: 0.98,
      chars: [_soul(0.95), _lev(0.6), _geo(0.6)],
      desc: 'The GOAT — flawless reads, relentless, fearless.'),
  _p('FP041', 'Doyle Brunson', 'The_Godfather',
      vpip: 0.30, pfr: 0.22, threeBet: 0.11, gto: 0.68, exploit: 0.55, risk: 1.2,
      oppRead: 0.9, chars: [_soul(0.8), _lev(0.6), _trap(0.6), _limp(0.8)],
      desc: 'The Godfather — aggressive, fearless pioneer.'),
  _p('FP042', 'Johnny Chan', 'Orient_Express',
      vpip: 0.27, pfr: 0.20, threeBet: 0.10, gto: 0.72, exploit: 0.55, oppRead: 0.9,
      chars: [_soul(0.85), _trap(0.7), _limp(0.6)],
      desc: 'Orient Express — masterful reads and timing.'),
  _p('FP043', 'Erik Seidel', 'Ageless_Legend',
      vpip: 0.25, pfr: 0.19, threeBet: 0.10, gto: 0.82, exploit: 0.4, oppRead: 0.85,
      chars: [_soul(0.8), _pos(0.6), _trap(0.5)],
      desc: 'Ageless, adaptive, disciplined legend.'),
  _p('FP044', 'Ted Forrest', 'Feel_Genius',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.75, exploit: 0.5, oppRead: 0.9,
      chars: [_soul(0.8)],
      desc: 'Feel-player genius with huge reads.'),
  _p('FP045', 'John Hennigan', 'Johnny_World',
      vpip: 0.27, pfr: 0.20, threeBet: 0.10, gto: 0.78, exploit: 0.45, oppRead: 0.8,
      chars: [_soul(0.6)],
      desc: 'Johnny World — fearless mixed-game action.'),
  _p('FP046', 'Antonio Esfandiari', 'The_Magician',
      vpip: 0.30, pfr: 0.22, threeBet: 0.11, gto: 0.72, exploit: 0.5, risk: 1.15,
      oppRead: 0.8, chars: [_soul(0.7), _lev(0.5)],
      desc: 'Charismatic, tricky live magician.'),
  _p('FP047', 'Scotty Nguyen', 'Prince_Of_Poker',
      vpip: 0.31, pfr: 0.23, threeBet: 0.12, gto: 0.7, exploit: 0.55, risk: 1.2,
      oppRead: 0.8, chars: [_soul(0.7), _lev(0.6), _trap(0.8), _sticky(0.6), _limp(0.7)],
      desc: 'Prince of Poker — tricky and aggressive.'),
  _p('FP048', 'Barry Greenstein', 'Robin_Hood',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.8, exploit: 0.4, oppRead: 0.8,
      chars: [_soul(0.6)],
      desc: 'Robin Hood of Poker — disciplined, analytical.'),
  _p('FP049', 'Howard Lederer', 'The_Professor',
      vpip: 0.22, pfr: 0.16, threeBet: 0.08, gto: 0.82, exploit: 0.4, oppRead: 0.75,
      chars: [_soul(0.6), _pos(0.6)],
      desc: 'The Professor — patient and cerebral.'),
  _p('FP050', 'Todd Brunson', 'Big_Game_Cash',
      vpip: 0.27, pfr: 0.20, threeBet: 0.10, gto: 0.75, exploit: 0.5, oppRead: 0.8,
      chars: [_soul(0.6), _trap(0.7), _sticky(0.5)],
      desc: 'Big-game cash specialist.'),
  _p('FP051', 'Bobby Baldwin', 'Cerebral_Champion',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.78, exploit: 0.4, oppRead: 0.75,
      chars: [_soul(0.6)],
      desc: 'Cerebral old-school champion.'),
  _p('FP052', 'Mike Sexton', 'The_Ambassador',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.78, exploit: 0.4, oppRead: 0.75,
      chars: [_soul(0.6)],
      desc: 'Ambassador of the game — solid and tricky.'),
  _p('FP053', 'Gabe Kaplan', 'Old_School_Sharp',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.72, exploit: 0.5, oppRead: 0.8,
      chars: [_soul(0.6)],
      desc: 'Sharp old-school live player.'),
  _p('FP054', 'Huck Seed', 'Unorthodox_AllRounder',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.78, exploit: 0.4, oppRead: 0.7,
      chars: [_soul(0.6)],
      desc: 'Unorthodox, tough all-arounder.'),
  _p('FP055', 'Allen Cunningham', 'Smooth_Positional',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.82, exploit: 0.35, oppRead: 0.75,
      chars: [_soul(0.6), _pos(0.6)],
      desc: 'Smooth, respected, positionally sound.'),
  _p('FP056', 'John Cernuto', 'Seasoned_Vet',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.75, exploit: 0.4, oppRead: 0.7,
      chars: [_soul(0.5), _limp(0.6)],
      desc: 'Miami John — seasoned veteran.'),

  // ---- Thinking / analytical pros ------------------------------------------
  _p('FP058', 'Jennifer Harman', 'Elite_Cash',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.85, exploit: 0.4, oppRead: 0.85,
      chars: [_soul(0.7), _trap(0.5), _cr(0.6)],
      desc: 'Elite high-stakes cash pro.'),
  _p('FP059', 'Annie Duke', 'Decision_Theorist',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.78, exploit: 0.45, oppRead: 0.85,
      chars: [_soul(0.7)],
      desc: 'Decision-theorist; sharp reads.'),
  _p('FP060', 'Kathy Liebert', 'Steady_Veteran',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.8, exploit: 0.35, oppRead: 0.7,
      chars: [_soul(0.5), _shutdown(0.6)],
      desc: 'Steady, aggressive veteran.'),
  _p('FP061', 'Jennifer Tilly', 'Action_Loving',
      vpip: 0.33, pfr: 0.24, threeBet: 0.12, gto: 0.68, exploit: 0.45, risk: 1.2,
      tilt: 0.7, chars: [_lev(0.6), _soul(0.4), _sticky(0.85), _chase(0.8)],
      desc: 'Loose, fearless, action-loving.'),
  _p('FP062', 'Cyndy Violette', 'Disciplined_Solid',
      vpip: 0.22, pfr: 0.16, threeBet: 0.08, gto: 0.82, exploit: 0.3,
      chars: [_shutdown(0.65)],
      desc: 'Disciplined, solid pro.'),

  // ---- Tight / nitty / mathematical ---------------------------------------
  _p('FP063', 'Allen Kessler', 'Chainsaw_Nit',
      vpip: 0.18, pfr: 0.12, threeBet: 0.04, gto: 0.8, exploit: 0.2, tilt: 0.7,
      chars: [_shutdown(0.8)],
      desc: 'Chainsaw — famously tight and value-driven.'),
  _p('FP064', 'Chris Ferguson', 'Jesus_GTO',
      vpip: 0.22, pfr: 0.16, threeBet: 0.08, gto: 0.95, exploit: 0.1,
      chars: [_pos(0.6)],
      desc: 'Jesus — mathematical and disciplined.'),
  _p('FP065', 'Jeff Lisandro', 'Mixed_Specialist',
      vpip: 0.20, pfr: 0.14, threeBet: 0.06, gto: 0.82, exploit: 0.3,
      chars: [_soul(0.6)],
      desc: 'Disciplined mixed-game specialist.'),
  _p('FP066', 'Tom McEvoy', 'ABC_Champion',
      vpip: 0.20, pfr: 0.14, threeBet: 0.06, gto: 0.8, exploit: 0.25,
      chars: [_limp(0.5), _shutdown(0.6)],
      desc: 'Conservative ABC champion.'),
  _p('FP067', 'Greg Raymer', 'Fossilman',
      vpip: 0.22, pfr: 0.16, threeBet: 0.08, gto: 0.82, exploit: 0.35,
      chars: [_soul(0.5), _shutdown(0.55)],
      desc: 'Fossilman — analytical and solid.'),

  // ---- Special ------------------------------------------------------------
  _p('FP068', 'Bing Diao', 'Analytical_Machine',
      vpip: 0.23, pfr: 0.17, threeBet: 0.09, gto: 0.95, exploit: 0.15, tilt: 0.97,
      oppRead: 0.6, chars: [_pos(0.85), _geo(0.5)],
      desc: 'Hyper-analytical, patient, near-unexploitable technician.'),

  // ---- Modern GTO high-rollers / solver-era regs --------------------------
  _p('FP069', 'Danny Tang', 'GTO_High_Roller',
      vpip: 0.25, pfr: 0.19, threeBet: 0.11, gto: 0.92, exploit: 0.2, risk: 1.1,
      chars: [_geo(0.6), _pos(0.7)],
      desc: 'Studious Hong Kong high-roller regular.'),
  _p('FP070', 'Paul Phua', 'Aggressive_Whale',
      vpip: 0.32, pfr: 0.20, threeBet: 0.10, gto: 0.72, exploit: 0.5, risk: 1.3,
      tilt: 0.6, chars: [_lev(0.6), _soul(0.5), _sticky(0.7), _chase(0.6)],
      desc: 'Loose, fearless super-high-roller businessman.'),
  _p('FP071', 'Nacho Barbero', 'LAG_Grinder',
      vpip: 0.31, pfr: 0.23, threeBet: 0.13, gto: 0.82, exploit: 0.4, risk: 1.25,
      chars: [_lev(0.6), _pos(0.6), _float(0.65), _cr(0.65)],
      desc: 'Aggressive, high-volume Argentine grinder.'),
  _p('FP072', 'Christoph Vogelsang', 'GTO_Technician',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.96, exploit: 0.1,
      chars: [_geo(0.6), _pos(0.7)],
      desc: 'Quiet, near-unexploitable super-high-roller.'),
  _p('FP073', 'Elton Tsang', 'Aggressive_Whale',
      vpip: 0.31, pfr: 0.21, threeBet: 0.11, gto: 0.75, exploit: 0.45, risk: 1.3,
      tilt: 0.7, chars: [_lev(0.6), _sticky(0.7)],
      desc: 'Big-game gambler with a huge aggressive streak.'),
  _p('FP074', 'Seth Davies', 'GTO_High_Roller',
      vpip: 0.26, pfr: 0.20, threeBet: 0.12, gto: 0.92, exploit: 0.25, risk: 1.15,
      chars: [_geo(0.6), _pos(0.7)],
      desc: 'Modern solver-era high-roller crusher.'),
  _p('FP075', 'Tan Xuan', 'Aggressive_High_Roller',
      vpip: 0.29, pfr: 0.21, threeBet: 0.12, gto: 0.82, exploit: 0.4, risk: 1.25,
      chars: [_lev(0.6), _geo(0.5)],
      desc: 'Aggressive Asian super-high-roller regular.'),
  _p('FP076', 'Daniel Cates', 'Unorthodox_Genius',
      vpip: 0.30, pfr: 0.22, threeBet: 0.13, gto: 0.85, exploit: 0.5, risk: 1.3,
      oppRead: 0.85, chars: [_soul(0.7), _lev(0.7), _geo(0.6), _float(0.8), _cr(0.8)],
      desc: 'Jungleman — creative, exploitative online legend.'),
  _p('FP077', 'Eric Persson', 'Action_Whale',
      vpip: 0.34, pfr: 0.24, threeBet: 0.12, gto: 0.65, exploit: 0.55, risk: 1.4,
      tilt: 0.4, chars: [_lev(0.7), _soul(0.4), _sticky(0.8), _chase(0.75)],
      desc: 'Maverick action-junkie; maximum gamble.'),
  _p('FP078', 'Wang Ye', 'Aggressive_Live',
      vpip: 0.30, pfr: 0.21, threeBet: 0.11, gto: 0.76, exploit: 0.45, risk: 1.2,
      chars: [_lev(0.6)],
      desc: 'Aggressive Chinese high-stakes live player.'),
  _p('FP079', 'Chris Brewer', 'GTO_High_Roller',
      vpip: 0.26, pfr: 0.20, threeBet: 0.12, gto: 0.93, exploit: 0.22, risk: 1.15,
      chars: [_geo(0.7), _pos(0.7)],
      desc: 'Dominant modern super-high-roller technician.'),
  _p('FP080', 'Sean Winter', 'Aggressive_High_Roller',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.85, exploit: 0.35, risk: 1.25,
      chars: [_lev(0.6), _geo(0.6)],
      desc: 'Fearless, aggressive high-roller regular.'),
  _p('FP081', 'Brian Kim', 'GTO_Reg',
      vpip: 0.25, pfr: 0.19, threeBet: 0.11, gto: 0.9, exploit: 0.25,
      chars: [_pos(0.6)],
      desc: 'Solid, disciplined high-roller regular.'),
  _p('FP082', 'Nick Petrangelo', 'GTO_Technician',
      vpip: 0.25, pfr: 0.19, threeBet: 0.11, gto: 0.94, exploit: 0.15,
      chars: [_geo(0.6), _pos(0.7)],
      desc: 'Coach-sharp, near-unexploitable technician.'),
  _p('FP083', 'Espen Jorstad', 'Balanced_Aggressor',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.9, exploit: 0.3, risk: 1.15,
      chars: [_pos(0.7), _lev(0.5), _bubble(0.7)],
      desc: 'Balanced, aggressive Main Event champion.'),
  _p('FP084', 'Xu Liang', 'Aggressive_Live',
      vpip: 0.29, pfr: 0.21, threeBet: 0.11, gto: 0.76, exploit: 0.45, risk: 1.2,
      chars: [_lev(0.6)],
      desc: 'Aggressive Asian tournament crusher.'),
  _p('FP085', 'Brandon Wilson', 'Aggressive_High_Roller',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.84, exploit: 0.4, risk: 1.25,
      chars: [_lev(0.6)],
      desc: 'Aggressive high-roller cash and tournament player.'),
  _p('FP086', 'David Yan', 'GTO_Technician',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.94, exploit: 0.18,
      chars: [_geo(0.6), _pos(0.7)],
      desc: 'Studious, precise New Zealand technician.'),
  _p('FP087', 'Sosia Jiang', 'Aggressive_High_Roller',
      vpip: 0.28, pfr: 0.20, threeBet: 0.11, gto: 0.82, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive, ambitious high-roller regular.'),
  _p('FP088', 'Luc Greenwood', 'GTO_High_Roller',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.92, exploit: 0.25, risk: 1.1,
      chars: [_pos(0.7), _geo(0.5)],
      desc: 'Disciplined member of the Greenwood high-roller family.'),

  // ---- Grinders, coaches, and mixed reputations ---------------------------
  _p('FP089', 'Chris Moneymaker', 'Aggressive_Amateur',
      vpip: 0.31, pfr: 0.21, threeBet: 0.10, gto: 0.7, exploit: 0.45, risk: 1.2,
      tilt: 0.6, chars: [_lev(0.5), _soul(0.4)],
      desc: 'The poker-boom everyman; loose and fearless.'),
  _p('FP090', 'Ebony Kenney', 'Solid_Reg',
      vpip: 0.25, pfr: 0.19, threeBet: 0.10, gto: 0.87, exploit: 0.35,
      chars: [_pos(0.6)],
      desc: 'Solid, well-studied modern tournament reg.'),
  _p('FP091', 'Aleksandr Zubov', 'Aggressive_Reg',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.83, exploit: 0.35, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive Russian high-stakes regular.'),
  _p('FP092', 'Dylan Weisman', 'GTO_Reg',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.9, exploit: 0.3, risk: 1.1,
      chars: [_pos(0.6)],
      desc: 'Studious, aggressive high-roller regular.'),
  _p('FP093', 'Calvin Lee', 'Solid_Grinder',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.85, exploit: 0.35,
      desc: 'Steady, well-rounded tournament grinder.'),
  _p('FP094', 'Bill Perkins', 'Action_Whale',
      vpip: 0.33, pfr: 0.22, threeBet: 0.11, gto: 0.66, exploit: 0.5, risk: 1.4,
      tilt: 0.5, chars: [_lev(0.6), _soul(0.4), _sticky(0.75), _chase(0.7)],
      desc: 'High-stakes gambler who loves the action.'),
  _p('FP095', 'Shaun Deeb', 'Exploitative_Grinder',
      vpip: 0.30, pfr: 0.22, threeBet: 0.13, gto: 0.8, exploit: 0.55, risk: 1.25,
      oppRead: 0.8, chars: [_lev(0.6), _soul(0.6), _float(0.7), _bubble(0.9), _under(0.7), _cr(0.65)],
      desc: 'Relentless, exploit-heavy high-volume grinder.'),
  _p('FP096', 'Naoya Kihara', 'Solid_Technician',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.9, exploit: 0.25,
      chars: [_pos(0.6)],
      desc: 'Disciplined, studious Japanese pro.'),
  _p('FP097', 'Jesse Lonis', 'Aggressive_High_Roller',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.85, exploit: 0.4, risk: 1.25,
      chars: [_lev(0.6), _geo(0.5)],
      desc: 'Aggressive, rising high-roller crusher.'),
  _p('FP098', 'Michael Moncek', 'Solid_Reg',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.86, exploit: 0.35,
      desc: 'Solid, consistent tournament regular.'),
  _p('FP099', 'Joshua Reichard', 'Aggressive_Grinder',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.8, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive, prolific high-stakes tournament winner.'),
  _p('FP100', 'Calvin Anderson', 'Mixed_Grinder',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.88, exploit: 0.35,
      chars: [_pos(0.6)],
      desc: 'Versatile, disciplined mixed-game grinder.'),
  _p('FP101', 'Martin Zamani', 'Aggressive_LAG',
      vpip: 0.31, pfr: 0.23, threeBet: 0.13, gto: 0.78, exploit: 0.45, risk: 1.3,
      tilt: 0.65, chars: [_lev(0.6), _float(0.7), _cr(0.7)],
      desc: 'Fiery, aggressive tournament LAG.'),
  _p('FP102', 'Lucas Jumalon', 'Solid_Reg',
      vpip: 0.26, pfr: 0.19, threeBet: 0.11, gto: 0.87, exploit: 0.35,
      desc: 'Steady, well-studied tournament regular.'),
  _p('FP103', 'Myles Mullaly', 'Aggressive_Reg',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.84, exploit: 0.35, risk: 1.15,
      chars: [_lev(0.5)],
      desc: 'Aggressive, modern high-roller regular.'),
  _p('FP104', 'Marco Johnson', 'Solid_Veteran',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.84, exploit: 0.35,
      desc: 'Consistent, solid tournament veteran.'),
  _p('FP105', 'Nicholas Pupillo', 'Aggressive_Grinder',
      vpip: 0.29, pfr: 0.21, threeBet: 0.11, gto: 0.79, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive high-volume tournament grinder.'),
  _p('FP106', 'Ren Lin', 'Aggressive_High_Roller',
      vpip: 0.28, pfr: 0.20, threeBet: 0.11, gto: 0.82, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive high-roller tournament crusher.'),
  _p('FP107', 'Jamie Dwan', 'Solid_Reg',
      vpip: 0.26, pfr: 0.19, threeBet: 0.11, gto: 0.85, exploit: 0.35,
      chars: [_pos(0.6)],
      desc: 'Solid, aggressive European tournament reg.'),
  _p('FP108', 'Marius Kudzmanas', 'Aggressive_Reg',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.82, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive online-bred high-stakes reg.'),
  _p('FP109', 'Antonio Vargas', 'Aggressive_MTT',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.83, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5), _pos(0.6)],
      desc: 'Aggressive, talented young tournament crusher.'),
  _p('FP110', 'Martin Kabrhel', 'Chaotic_Whale',
      vpip: 0.34, pfr: 0.24, threeBet: 0.13, gto: 0.68, exploit: 0.55, risk: 1.4,
      tilt: 0.4, oppRead: 0.7, chars: [_lev(0.8), _soul(0.5), _sticky(0.65), _float(0.5), _blowup(0.7)],
      desc: 'Wild, table-talking, chaotic high-roller.'),
  _p('FP111', 'Punnat Punsri', 'Solid_Reg',
      vpip: 0.26, pfr: 0.19, threeBet: 0.11, gto: 0.87, exploit: 0.3,
      chars: [_pos(0.6)],
      desc: 'Studious, disciplined Thai tournament reg.'),
  _p('FP112', 'Matthew Vengrin', 'Aggressive_Grinder',
      vpip: 0.28, pfr: 0.21, threeBet: 0.11, gto: 0.8, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive high-volume tournament grinder.'),
  _p('FP113', 'Christopher Nguyen', 'Aggressive_Reg',
      vpip: 0.28, pfr: 0.20, threeBet: 0.11, gto: 0.8, exploit: 0.4, risk: 1.15,
      chars: [_lev(0.5)],
      desc: 'Aggressive, well-rounded tournament regular.'),
  _p('FP114', 'Jonathan Little', 'Coach_Solid',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.9, exploit: 0.4, oppRead: 0.75,
      chars: [_pos(0.6), _soul(0.5), _under(0.7)],
      desc: 'Prolific coach; solid, teaching-clean fundamentals.'),
  _p('FP115', 'Jonathan Turner', 'Aggressive_Reg',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.82, exploit: 0.4, risk: 1.15,
      chars: [_lev(0.5)],
      desc: 'Aggressive, adaptable tournament regular.'),
  _p('FP116', 'Jeffrey Madsen', 'Solid_Veteran',
      vpip: 0.25, pfr: 0.19, threeBet: 0.10, gto: 0.84, exploit: 0.35,
      desc: 'Young-champion-turned-steady veteran.'),
  _p('FP117', 'Lauri Saaskilahti', 'Aggressive_Reg',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.83, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5), _pos(0.6)],
      desc: 'Aggressive Finnish online-bred regular.'),

  // ---- Content creators / streamers / personalities -----------------------
  _p('FP118', 'Liv Boeree', 'Analytical_Solid',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.85, exploit: 0.35, oppRead: 0.7,
      chars: [_soul(0.5), _pos(0.6)],
      desc: 'Analytical, science-minded solid pro.'),
  _p('FP119', 'Loni Hui', 'Aggressive_Reg',
      vpip: 0.28, pfr: 0.20, threeBet: 0.11, gto: 0.82, exploit: 0.4, risk: 1.15,
      chars: [_lev(0.5)],
      desc: 'Aggressive, sharp tournament regular.'),
  _p('FP120', 'Andrew Neeme', 'Solid_Live',
      vpip: 0.27, pfr: 0.19, threeBet: 0.10, gto: 0.8, exploit: 0.4, oppRead: 0.7,
      chars: [_soul(0.5), _under(0.6)],
      desc: 'Vlog-era live cash grinder; patient and solid.'),
  _p('FP121', 'Mariano Grandoli', 'Aggressive_Live',
      vpip: 0.30, pfr: 0.21, threeBet: 0.11, gto: 0.76, exploit: 0.45, risk: 1.2,
      tilt: 0.7, chars: [_lev(0.5), _soul(0.4)],
      desc: 'High-stakes cash streamer; loose and aggressive.'),
  _p('FP122', 'Corey Eyring', 'Solid_Live',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.82, exploit: 0.4,
      chars: [_soul(0.4)],
      desc: 'Steady live cash-game vlogger and grinder.'),
  _p('FP123', 'Ryan DePaulo', 'Recreational_LAG',
      vpip: 0.32, pfr: 0.21, threeBet: 0.10, gto: 0.68, exploit: 0.45, risk: 1.25,
      tilt: 0.55, chars: [_lev(0.5), _soul(0.4), _sticky(0.7), _chase(0.65)],
      desc: 'Degenerate-brand vlogger; loose and fearless.'),
  _p('FP124', 'David Kaye', 'Solid_Live',
      vpip: 0.27, pfr: 0.19, threeBet: 0.10, gto: 0.8, exploit: 0.4,
      chars: [_soul(0.4)],
      desc: 'Live cash content creator; solid fundamentals.'),
  _p('FP125', 'Bart Hanson', 'Coach_Exploit',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.82, exploit: 0.5, oppRead: 0.8,
      chars: [_soul(0.6), _pos(0.6), _under(0.9)],
      desc: 'Live-cash coach; exploit-heavy, reads-driven.'),
  _p('FP126', 'James Sweeney', 'Solid_Live',
      vpip: 0.27, pfr: 0.19, threeBet: 0.10, gto: 0.8, exploit: 0.4,
      chars: [_soul(0.4)],
      desc: 'Live cash grinder and content creator.'),
  _p('FP127', 'Alec Torelli', 'Balanced_Live',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.83, exploit: 0.4, oppRead: 0.7,
      chars: [_soul(0.5), _pos(0.6), _under(0.6)],
      desc: 'Balanced live pro and coach.'),
  _p('FP128', 'Kevin Martin', 'Aggressive_Stream',
      vpip: 0.29, pfr: 0.21, threeBet: 0.11, gto: 0.8, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive tournament streamer.'),
  _p('FP129', 'Marc Goone', 'Aggressive_Content',
      vpip: 0.30, pfr: 0.21, threeBet: 0.11, gto: 0.76, exploit: 0.45, risk: 1.25,
      chars: [_lev(0.5), _soul(0.4)],
      desc: 'Aggressive content-creator and cash player.'),
  _p('FP130', 'Nathan Williams', 'Coach_Nit',
      vpip: 0.22, pfr: 0.15, threeBet: 0.06, gto: 0.88, exploit: 0.4, oppRead: 0.7,
      chars: [_pos(0.6), _under(0.65), _shutdown(0.7)],
      desc: 'BlackRain79 — tight-aggressive micro-stakes coach.'),
  _p('FP131', 'Lex Veldhuis', 'Aggressive_Stream',
      vpip: 0.30, pfr: 0.22, threeBet: 0.12, gto: 0.8, exploit: 0.4, risk: 1.25,
      tilt: 0.7, chars: [_lev(0.6)],
      desc: 'Beloved aggressive tournament streamer.'),
  _p('FP132', 'Matt Berkey', 'Exploit_Cash',
      vpip: 0.28, pfr: 0.20, threeBet: 0.11, gto: 0.83, exploit: 0.55, risk: 1.2,
      oppRead: 0.85, chars: [_soul(0.7), _lev(0.6), _under(0.8), _cr(0.7)],
      desc: 'High-stakes cash exploiter and coach.'),
  _p('FP133', 'Will Kassouf', 'Speech_Play_LAG',
      vpip: 0.32, pfr: 0.21, threeBet: 0.11, gto: 0.7, exploit: 0.5, risk: 1.25,
      tilt: 0.6, oppRead: 0.75, chars: [_soul(0.6), _lev(0.6), _blowup(0.6)],
      desc: 'Speech-play specialist; loose, needling, aggressive.'),
  _p('FP134', 'Abby Merk', 'Solid_Reg',
      vpip: 0.26, pfr: 0.19, threeBet: 0.11, gto: 0.85, exploit: 0.35,
      chars: [_pos(0.6)],
      desc: 'Studious, solid tournament regular and creator.'),
  _p('FP135', 'Alexander Wolfgang', 'Solid_Live',
      vpip: 0.27, pfr: 0.19, threeBet: 0.10, gto: 0.8, exploit: 0.4,
      chars: [_soul(0.4)],
      desc: 'Live cash grinder and content creator.'),
  _p('FP136', 'Gregory Liow', 'Aggressive_Reg',
      vpip: 0.28, pfr: 0.20, threeBet: 0.11, gto: 0.82, exploit: 0.4, risk: 1.15,
      chars: [_lev(0.5)],
      desc: 'Aggressive Southeast-Asian tournament reg.'),
  _p('FP137', 'Frank Cucchiara', 'Solid_Live',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.8, exploit: 0.4,
      chars: [_soul(0.4)],
      desc: 'Live cash player and content creator.'),
  _p('FP138', 'Kitty Kuo', 'Aggressive_Live',
      vpip: 0.30, pfr: 0.21, threeBet: 0.11, gto: 0.75, exploit: 0.45, risk: 1.2,
      tilt: 0.65, chars: [_lev(0.5), _soul(0.4)],
      desc: 'Aggressive, fearless Taiwanese live pro.'),
  _p('FP139', 'Han Feng', 'Aggressive_Live',
      vpip: 0.29, pfr: 0.21, threeBet: 0.11, gto: 0.77, exploit: 0.45, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive Asian high-stakes tournament player.'),
  _p('FP140', 'Andreas Wagner', 'Solid_Reg',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.85, exploit: 0.35,
      desc: 'Steady, disciplined European tournament reg.'),
  _p('FP141', 'Victoria Coren', 'Composed_Solid',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.82, exploit: 0.4, oppRead: 0.75,
      chars: [_soul(0.5)],
      desc: 'Composed, sharp two-time EPT champion.'),

  // ---- Cash-game giants ---------------------------------------------------
  _p('FP142', 'Tom Dwan', 'Fearless_Online_Legend',
      vpip: 0.34, pfr: 0.26, threeBet: 0.14, gto: 0.72, exploit: 0.75, risk: 1.35,
      tilt: 0.95, oppRead: 0.92,
      chars: [_soul(0.9), _lev(0.85), _geo(0.8), _float(0.8), _pos(0.7), _cr(0.6)],
      desc: 'durrrr — fearless, read-driven, enormous bluffs.'),
  _p('FP143', 'Chip Reese', 'Greatest_Cash_Player',
      vpip: 0.27, pfr: 0.19, threeBet: 0.09, gto: 0.8, exploit: 0.5,
      tilt: 0.98, oppRead: 0.95,
      chars: [_soul(0.9), _trap(0.6), _under(0.6), _pos(0.6)],
      desc: 'Widely called the finest cash player who ever lived.'),
  _p('FP144', 'Gus Hansen', 'The_Great_Dane',
      vpip: 0.42, pfr: 0.30, threeBet: 0.14, gto: 0.55, exploit: 0.8, risk: 1.3,
      tilt: 0.7, oppRead: 0.75,
      chars: [_float(0.85), _pos(0.75), _lev(0.7), _soul(0.6), _cr(0.6),
        _blowup(0.4)],
      desc: 'Wildly loose-aggressive; plays any two and outplays you after.'),
  _p('FP145', 'Viktor Blom', 'Isildur1',
      vpip: 0.38, pfr: 0.30, threeBet: 0.14, gto: 0.62, exploit: 0.8, risk: 1.45,
      tilt: 0.45, oppRead: 0.6,
      chars: [_lev(0.85), _blowup(0.85), _geo(0.8), _float(0.7), _cr(0.6)],
      desc: 'Isildur1 — breathtaking aggression and breathtaking swings.'),
  _p('FP146', 'Linus Loeliger', 'Modern_Cash_King',
      vpip: 0.27, pfr: 0.20, threeBet: 0.12, gto: 0.97, exploit: 0.15, risk: 1.1,
      tilt: 0.97,
      chars: [_geo(0.85), _pos(0.8), _cr(0.75), _under(0.5)],
      desc: 'The best online cash player alive; close to unexploitable.'),
  _p('FP147', 'Alan Keating', 'Action_Millionaire',
      vpip: 0.45, pfr: 0.30, threeBet: 0.12, gto: 0.42, exploit: 0.7, risk: 1.5,
      tilt: 0.6, oppRead: 0.5,
      chars: [_lev(0.8), _sticky(0.8), _geo(0.7), _chase(0.6), _blowup(0.5)],
      desc: 'Gambles enormous, calls light, makes the biggest games run.'),

  // ---- The Binion's-era old guard -----------------------------------------
  _p('FP148', 'Johnny Moss', 'Grand_Old_Man',
      vpip: 0.28, pfr: 0.19, threeBet: 0.08, gto: 0.6, exploit: 0.6,
      tilt: 0.9, oppRead: 0.88,
      chars: [_soul(0.8), _limp(0.8), _trap(0.6), _sticky(0.4)],
      desc: 'The Grand Old Man — the first world champion.'),
  _p('FP149', 'Dan Harrington', 'Action_Dan',
      vpip: 0.21, pfr: 0.14, threeBet: 0.05, gto: 0.85, exploit: 0.3,
      tilt: 0.96, oppRead: 0.8,
      chars: [_pos(0.7), _under(0.5), _trap(0.5)],
      desc: 'Patient to a fault, then suddenly and precisely aggressive.'),
  _p('FP150', 'T.J. Cloutier', 'Tournament_Warhorse',
      vpip: 0.24, pfr: 0.17, threeBet: 0.07, gto: 0.7, exploit: 0.45,
      oppRead: 0.85,
      chars: [_soul(0.7), _pos(0.6), _trap(0.5)],
      desc: 'Six bracelets and six Main Event final tables of hard-won feel.'),
  _p('FP151', 'Billy Baxter', 'Lowball_Legend',
      vpip: 0.24, pfr: 0.17, threeBet: 0.07, gto: 0.7, exploit: 0.4,
      tilt: 0.9, oppRead: 0.85,
      chars: [_soul(0.7), _trap(0.5)],
      desc: 'Lowball master; seven bracelets and an iron temperament.'),
  _p('FP152', 'Lyle Berman', 'Aggressive_Businessman',
      vpip: 0.30, pfr: 0.21, threeBet: 0.09, gto: 0.6, exploit: 0.5, risk: 1.25,
      tilt: 0.85,
      chars: [_lev(0.6), _sticky(0.4)],
      desc: 'Big-bet gambler and founder of the WPT.'),
  _p('FP153', 'Layne Flack', 'Back_to_Back',
      vpip: 0.33, pfr: 0.25, threeBet: 0.12, gto: 0.6, exploit: 0.65, risk: 1.3,
      tilt: 0.6, oppRead: 0.8,
      chars: [_soul(0.7), _lev(0.7), _float(0.7), _blowup(0.5)],
      desc: 'Back-to-Back Flack — ferocious natural talent.'),
  _p('FP154', 'David Ulliott', 'Devilfish',
      vpip: 0.32, pfr: 0.24, threeBet: 0.11, gto: 0.55, exploit: 0.7, risk: 1.3,
      tilt: 0.7, oppRead: 0.85,
      chars: [_soul(0.8), _lev(0.7), _float(0.6), _blowup(0.4)],
      desc: 'The Devilfish — needling, intimidating, deadly accurate reads.'),
  _p('FP155', 'Chau Giang', 'Big_Game_Fixture',
      vpip: 0.29, pfr: 0.20, threeBet: 0.08, gto: 0.7, exploit: 0.5,
      tilt: 0.8, oppRead: 0.85,
      chars: [_soul(0.7), _limp(0.6), _sticky(0.5)],
      desc: 'A permanent fixture of the Bellagio big game.'),
  _p('FP156', 'Freddy Deeb', 'Wily_Veteran',
      vpip: 0.30, pfr: 0.21, threeBet: 0.09, gto: 0.65, exploit: 0.55,
      oppRead: 0.85,
      chars: [_soul(0.75), _trap(0.6), _limp(0.5)],
      desc: 'Wily, talkative veteran of every big mixed game.'),
  _p('FP157', 'Barbara Enright', 'Trailblazer',
      vpip: 0.25, pfr: 0.18, threeBet: 0.08, gto: 0.7, exploit: 0.45,
      tilt: 0.88, oppRead: 0.8,
      chars: [_soul(0.65), _trap(0.5)],
      desc: 'Hall of Famer; the only woman to final-table the Main Event.'),

  // ---- Main Event champions -----------------------------------------------
  _p('FP158', 'Robert Varkonyi', 'Unlikely_Champion',
      vpip: 0.24, pfr: 0.16, threeBet: 0.06, gto: 0.6, exploit: 0.3, tilt: 0.7,
      chars: [_sticky(0.5)],
      desc: 'The 2002 champion nobody saw coming.'),
  _p('FP159', 'Jerry Yang', 'Prayerful_Aggressor',
      vpip: 0.33, pfr: 0.24, threeBet: 0.10, gto: 0.5, exploit: 0.6, risk: 1.3,
      tilt: 0.65,
      chars: [_lev(0.65), _blowup(0.4)],
      desc: 'Rode relentless pressure to the 2007 title.'),
  _p('FP160', 'Pius Heinz', 'German_Technician',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.88, exploit: 0.3,
      chars: [_pos(0.65), _cr(0.5)],
      desc: 'First German champion; online-schooled and technical.'),
  _p('FP161', 'Martin Jacobson', 'Ice_Cold_Swede',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.92, exploit: 0.25, tilt: 0.98,
      chars: [_pos(0.7), _under(0.6), _shutdown(0.3)],
      desc: 'Meticulously prepared and impossible to rattle.'),
  _p('FP162', 'Joe McKeehen', 'Dominant_Chipleader',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.87, exploit: 0.4, risk: 1.25,
      tilt: 0.9,
      chars: [_lev(0.8), _bubble(0.8), _pos(0.75)],
      desc: 'Bullied a final table from wire to wire in 2015.'),
  _p('FP163', 'Scott Blumstein', 'Online_Grinder_Champ',
      vpip: 0.30, pfr: 0.22, threeBet: 0.12, gto: 0.82, exploit: 0.45, risk: 1.2,
      chars: [_lev(0.6), _float(0.6)],
      desc: 'Online grinder who ran over the 2017 final table.'),
  _p('FP164', 'John Cynn', 'Patient_Marathoner',
      vpip: 0.23, pfr: 0.17, threeBet: 0.09, gto: 0.88, exploit: 0.3, tilt: 0.97,
      chars: [_pos(0.65), _under(0.55), _trap(0.5)],
      desc: 'Outlasted the longest heads-up match in Main Event history.'),
  _p('FP165', 'Hossein Ensan', 'Patient_Veteran',
      vpip: 0.21, pfr: 0.15, threeBet: 0.06, gto: 0.85, exploit: 0.25, tilt: 0.95,
      chars: [_trap(0.6), _under(0.6)],
      desc: 'Tight, patient, and unmoved by pressure.'),
  _p('FP166', 'Damian Salas', 'Steady_Argentine',
      vpip: 0.25, pfr: 0.18, threeBet: 0.09, gto: 0.84, exploit: 0.35,
      chars: [_pos(0.6)],
      desc: 'Steady Argentine who won the split 2020 title.'),
  _p('FP167', 'Daniel Weinman', 'Modern_Champion',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.9, exploit: 0.35, risk: 1.15,
      chars: [_pos(0.7), _geo(0.6), _cr(0.6)],
      desc: 'Won the largest Main Event ever assembled.'),
  _p('FP168', 'Jonathan Tamayo', 'Studied_Grinder',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.88, exploit: 0.35,
      oppRead: 0.7,
      chars: [_pos(0.65), _under(0.5)],
      desc: 'Long-time grinder who finally broke through in 2024.'),

  // ---- The modern high-roller circuit -------------------------------------
  _p('FP169', 'David Peters', 'Relentless_Grinder',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.93, exploit: 0.25,
      chars: [_pos(0.7), _geo(0.6), _bubble(0.7)],
      desc: 'Quietly one of the most consistent earners in the game.'),
  _p('FP170', "Steve O'Dwyer", 'Relentless_High_Roller',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.9, exploit: 0.35, risk: 1.2,
      chars: [_pos(0.75), _lev(0.6), _geo(0.6)],
      desc: 'Aggressive fixture of every European high roller.'),
  _p('FP171', 'Mikita Badziakouski', 'Quiet_Assassin',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.93, exploit: 0.2,
      chars: [_geo(0.65), _pos(0.7)],
      desc: 'Softly spoken, technically ruthless super-high-roller.'),
  _p('FP172', 'Dan Smith', 'Analytical_Crusher',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.9, exploit: 0.3,
      chars: [_pos(0.7), _bubble(0.7)],
      desc: 'Analytical, disciplined, and brutal on a bubble.'),
  _p('FP173', 'Igor Kurganov', 'Cerebral_Aggressor',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.9, exploit: 0.3, oppRead: 0.7,
      chars: [_soul(0.5), _pos(0.7), _geo(0.55)],
      desc: 'Cerebral, theory-first high roller.'),
  _p('FP174', 'Ole Schemion', 'Young_Phenom',
      vpip: 0.31, pfr: 0.23, threeBet: 0.13, gto: 0.85, exploit: 0.45, risk: 1.25,
      chars: [_lev(0.65), _pos(0.75), _float(0.6)],
      desc: 'Fearless German prodigy of the early solver era.'),
  _p('FP175', 'Sam Greenwood', 'Disciplined_Roller',
      vpip: 0.25, pfr: 0.19, threeBet: 0.11, gto: 0.93, exploit: 0.22,
      chars: [_pos(0.7), _under(0.5)],
      desc: 'The disciplined half of the Greenwood high-roller family.'),
  _p('FP176', 'Rainer Kempe', 'German_Technician',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.92, exploit: 0.25,
      chars: [_geo(0.6), _pos(0.7)],
      desc: 'Precise German technician with a huge high-roller record.'),
  _p('FP177', 'Juan Pardo', 'Spanish_Aggressor',
      vpip: 0.31, pfr: 0.24, threeBet: 0.14, gto: 0.9, exploit: 0.4, risk: 1.3,
      chars: [_geo(0.75), _pos(0.75), _lev(0.7), _cr(0.65)],
      desc: 'Explosive Spanish talent; enormous sizings, sound theory.'),
  _p('FP178', 'Sergi Reixach', 'Aggressive_Spaniard',
      vpip: 0.30, pfr: 0.23, threeBet: 0.13, gto: 0.88, exploit: 0.4, risk: 1.25,
      chars: [_lev(0.65), _pos(0.7)],
      desc: 'Hard-charging Spanish high roller.'),
  _p('FP179', 'Artur Martirosian', 'Russian_Technician',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.92, exploit: 0.3,
      chars: [_pos(0.7), _geo(0.6)],
      desc: 'Online-bred Russian technician turned live crusher.'),
  _p('FP180', 'Orpen Kisacikoglu', 'Cash_Game_Specialist',
      vpip: 0.29, pfr: 0.21, threeBet: 0.11, gto: 0.88, exploit: 0.4,
      oppRead: 0.75,
      chars: [_soul(0.6), _pos(0.65), _cr(0.6)],
      desc: 'Cash-game specialist who crosses over and wins.'),
  _p('FP181', 'Jake Schindler', 'High_Volume_Roller',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.85, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.65), _bubble(0.7)],
      desc: 'Enormous volume across the high-roller circuit.'),
  _p('FP182', 'Ali Imsirovic', 'Aggressive_Prodigy',
      vpip: 0.31, pfr: 0.23, threeBet: 0.13, gto: 0.85, exploit: 0.45, risk: 1.25,
      chars: [_lev(0.7), _pos(0.75), _float(0.65)],
      desc: 'Prodigiously aggressive; a divisive figure in the game.'),
  _p('FP183', 'Anthony Zinno', 'Complete_Player',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.9, exploit: 0.35,
      oppRead: 0.75,
      chars: [_pos(0.7), _cr(0.6), _soul(0.5)],
      desc: 'Complete player — WPT titles and bracelets in every format.'),
  _p('FP184', 'Darren Elias', 'WPT_Record_Holder',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.9, exploit: 0.35,
      chars: [_pos(0.75), _bubble(0.7), _geo(0.55)],
      desc: 'Holds the record for WPT titles won.'),
  _p('FP185', 'Shannon Shorr', 'Steady_Professional',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.9, exploit: 0.3,
      chars: [_pos(0.7), _under(0.5)],
      desc: 'Two decades of steady, thoughtful professionalism.'),
  _p('FP186', 'Chino Rheem', 'Streaky_Gambler',
      vpip: 0.33, pfr: 0.24, threeBet: 0.11, gto: 0.6, exploit: 0.6, risk: 1.3,
      tilt: 0.5,
      chars: [_lev(0.65), _blowup(0.6), _chase(0.5)],
      desc: 'Streaky, fearless gambler who keeps finding final tables.'),
  _p('FP187', 'Vanessa Rousso', 'Lady_Maverick',
      vpip: 0.29, pfr: 0.21, threeBet: 0.11, gto: 0.8, exploit: 0.45, risk: 1.15,
      chars: [_pos(0.7), _lev(0.5)],
      desc: 'Game-theory-minded aggressor from the boom era.'),

  // ---- Online legends ------------------------------------------------------
  _p('FP188', 'Niklas Astedt', 'Online_MTT_King',
      vpip: 0.28, pfr: 0.22, threeBet: 0.13, gto: 0.95, exploit: 0.25, risk: 1.15,
      chars: [_pos(0.8), _bubble(0.8), _geo(0.7), _cr(0.65)],
      desc: 'The most feared online tournament player of the era.'),
  _p('FP189', 'Chris Moorman', 'Volume_Machine',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.9, exploit: 0.3,
      chars: [_pos(0.7), _bubble(0.65)],
      desc: 'More online cashes than anyone who has ever played.'),
  _p('FP190', 'Ben Sulsky', 'Sauce123',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.95, exploit: 0.2, risk: 1.15,
      chars: [_geo(0.8), _cr(0.7), _pos(0.7)],
      desc: 'Sauce123 — a theory pioneer of high-stakes online.'),
  _p('FP191', 'Timofey Kuznetsov', 'Trueteller',
      vpip: 0.30, pfr: 0.23, threeBet: 0.13, gto: 0.9, exploit: 0.35, risk: 1.3,
      chars: [_geo(0.75), _lev(0.7), _float(0.6)],
      desc: 'Trueteller — savage, creative nosebleed aggression.'),
  _p('FP192', 'Wiktor Malinowski', 'Limitless',
      vpip: 0.32, pfr: 0.24, threeBet: 0.14, gto: 0.9, exploit: 0.4, risk: 1.35,
      chars: [_geo(0.8), _lev(0.75), _pos(0.75), _cr(0.7)],
      desc: 'Limitless — relentless pressure at the very top stakes.'),

  // ---- Mixed-game specialists ---------------------------------------------
  _p('FP193', 'Yuri Dzivielevski', 'Mixed_Game_Master',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.94, exploit: 0.3, tilt: 0.95,
      chars: [_pos(0.7), _cr(0.7), _under(0.55)],
      desc: 'Brazilian master of every mixed discipline.'),
  _p('FP194', 'Dan Zack', 'Mixed_Game_Technician',
      vpip: 0.25, pfr: 0.18, threeBet: 0.09, gto: 0.93, exploit: 0.28,
      chars: [_cr(0.65), _under(0.6)],
      desc: 'Studious mixed-game technician and Player of the Year.'),
  _p('FP195', 'Adam Friedman', 'Dealers_Choice_King',
      vpip: 0.26, pfr: 0.18, threeBet: 0.08, gto: 0.88, exploit: 0.4,
      oppRead: 0.8,
      chars: [_soul(0.6), _trap(0.6)],
      desc: 'Three consecutive Dealers Choice bracelets — unrepeated.'),
  _p('FP196', 'Brian Hastings', 'Online_Convert',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.92, exploit: 0.3,
      chars: [_pos(0.7), _cr(0.6)],
      desc: 'Online nosebleed veteran turned mixed-game bracelet hunter.'),
  _p('FP197', 'Robert Mizrachi', 'Mixed_Game_Mizrachi',
      vpip: 0.28, pfr: 0.20, threeBet: 0.09, gto: 0.85, exploit: 0.4,
      oppRead: 0.75,
      chars: [_soul(0.55), _trap(0.55)],
      desc: 'The other bracelet-winning Mizrachi; a mixed-game specialist.'),

  // ---- Cash personalities and creators ------------------------------------
  _p('FP198', 'Joey Ingram', 'Poker_Detective',
      vpip: 0.30, pfr: 0.21, threeBet: 0.10, gto: 0.7, exploit: 0.55,
      tilt: 0.7, oppRead: 0.8,
      chars: [_soul(0.7), _float(0.6)],
      desc: "Poker's investigator; obsessive, curious, unafraid."),
  _p('FP199', 'Jaman Burton', 'Aggressive_Creator',
      vpip: 0.31, pfr: 0.22, threeBet: 0.11, gto: 0.72, exploit: 0.55, risk: 1.2,
      tilt: 0.7,
      chars: [_lev(0.6), _float(0.6), _soul(0.5)],
      desc: 'Personable creator with a genuinely aggressive live game.'),
  _p('FP200', 'Nick Vertucci', 'Live_Cash_Regular',
      vpip: 0.29, pfr: 0.20, threeBet: 0.09, gto: 0.7, exploit: 0.5, tilt: 0.65,
      chars: [_soul(0.5), _sticky(0.5)],
      desc: 'Live cash regular and co-host of the LATB era.'),
  _p('FP201', 'Jean-Robert Bellande', 'Broke_Living',
      vpip: 0.36, pfr: 0.25, threeBet: 0.11, gto: 0.55, exploit: 0.65, risk: 1.35,
      tilt: 0.5, oppRead: 0.7,
      chars: [_lev(0.7), _sticky(0.6), _blowup(0.55), _chase(0.5)],
      desc: 'Broke Living — action junkie with real game underneath.'),
  _p('FP202', 'Nik Airball', 'Aggro_Provocateur',
      vpip: 0.42, pfr: 0.31, threeBet: 0.14, gto: 0.55, exploit: 0.75, risk: 1.5,
      tilt: 0.5, oppRead: 0.5,
      chars: [_lev(0.85), _geo(0.75), _float(0.7), _blowup(0.6)],
      desc: 'Provocative, hyper-aggressive, allergic to a small pot.'),
  _p('FP203', 'Wesley Fei', 'High_Stakes_Gambler',
      vpip: 0.40, pfr: 0.28, threeBet: 0.13, gto: 0.5, exploit: 0.7, risk: 1.45,
      tilt: 0.55,
      chars: [_lev(0.8), _sticky(0.7), _chase(0.55), _blowup(0.5)],
      desc: 'Fearless big-bet gambler from the streamed cash boom.'),

  // ---- Theorists -----------------------------------------------------------
  _p('FP204', 'David Sklansky', 'Theory_Author',
      vpip: 0.22, pfr: 0.16, threeBet: 0.08, gto: 0.88, exploit: 0.2, tilt: 0.9,
      chars: [_under(0.6), _pos(0.6)],
      desc: 'The theorist who taught a generation to think in expectation.'),
  _p('FP205', 'Mike Caro', 'Mad_Genius',
      vpip: 0.28, pfr: 0.19, threeBet: 0.08, gto: 0.55, exploit: 0.7,
      tilt: 0.85, oppRead: 0.95,
      chars: [_soul(0.9), _float(0.6), _under(0.5)],
      desc: 'The Mad Genius — tells, psychology, and pure read-craft.'),
];
