import 'package:monte/core/domain/ai/player_profile.dart';

/// A curated pack of well-known pros, each approximated along the profile axes:
/// preflop frequencies (VPIP/PFR/3-bet), the GTO↔exploit lean, bet sizing
/// (`risk`), and signature-move characteristics (soul read, geometric overbet,
/// positional warfare, leverage pressure). These are *style approximations* from
/// each player's reputation, not exact clones — and every one is calibrator-
/// feasible (a real open range, a VPIP>PFR gap, 3-bet ≤ 0.14). Spread into
/// `builtInProfiles`, so they appear in the tournament lobby and play their style.

PlayerCharacteristic _soul(double p) =>
    PlayerCharacteristic(id: 'Soul_Read', proficiency: p);
PlayerCharacteristic _geo(double p) =>
    PlayerCharacteristic(id: 'Geometric_Overbet_Execution', proficiency: p);
PlayerCharacteristic _pos(double p) =>
    PlayerCharacteristic(id: 'Positional_Warfare', proficiency: p);
PlayerCharacteristic _lev(double p) =>
    PlayerCharacteristic(id: 'Leverage_Pressure', proficiency: p);

PlayerProfile _p(
  String id,
  String name,
  String archetype, {
  required double vpip,
  required double pfr,
  required double threeBet,
  required double gto,
  double exploit = 0.3,
  double risk = 1.0,
  double tilt = 0.92,
  double oppRead = 0.6,
  List<PlayerCharacteristic> chars = const [],
  required String desc,
}) =>
    PlayerProfile(
      id: id,
      name: name,
      archetype: archetype,
      skill: 1.0,
      strategicBaseline: StrategicBaseline(
        vpipTarget: vpip,
        pfrTarget: pfr,
        threeBetFrequency: threeBet,
        gtoAdherenceWeight: gto,
      ),
      behavioralModifiers: BehavioralModifiers(
        tiltResistance: tilt,
        exploitativeWeight: exploit,
        riskPremiumCoefficient: risk,
        weightOnOpponentHistory: oppRead,
      ),
      generalTraits: const GeneralTraits(
        positionAwareness: 0.9,
        potOdds: 0.9,
        impliedOdds: 0.85,
      ),
      characteristics: chars,
      description: desc,
    );

/// The famous-pro roster (spread into `builtInProfiles`).
final List<PlayerProfile> famousPros = [
  // ---- Modern / solver-era GTO aggressors ---------------------------------
  _p('FP001', 'Stephen Chidwick', 'GTO_Technician',
      vpip: 0.25, pfr: 0.19, threeBet: 0.11, gto: 0.95, exploit: 0.12,
      chars: [_geo(0.6), _pos(0.7)],
      desc: 'Studious, near-unexploitable high-stakes technician.'),
  _p('FP002', 'Fedor Holz', 'GTO_Wunderkind',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.93, exploit: 0.25, risk: 1.15,
      chars: [_geo(0.7), _pos(0.7), _lev(0.5)],
      desc: 'Aggressive, disciplined solver-era great.'),
  _p('FP003', 'Justin Bonomo', 'GTO_High_Roller',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.93, exploit: 0.25, risk: 1.15,
      chars: [_geo(0.7), _pos(0.7)],
      desc: 'Balanced GTO crusher across every format.'),
  _p('FP004', 'Jason Koon', 'GTO_High_Roller',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.93, exploit: 0.25, risk: 1.15,
      chars: [_geo(0.7), _pos(0.7)],
      desc: "An athlete's discipline applied to top-tier GTO."),
  _p('FP005', 'Adrian Mateos', 'GTO_Aggressor',
      vpip: 0.27, pfr: 0.21, threeBet: 0.12, gto: 0.9, exploit: 0.3, risk: 1.2,
      chars: [_pos(0.8), _lev(0.5), _geo(0.6)],
      desc: 'Precise, aggressive European GTO star.'),
  _p('FP006', 'Bryn Kenney', 'Fearless_High_Roller',
      vpip: 0.29, pfr: 0.22, threeBet: 0.13, gto: 0.88, exploit: 0.35, risk: 1.35,
      chars: [_lev(0.8), _geo(0.7), _pos(0.6)],
      desc: 'Fearless high-roller; relentless aggression and big sizing.'),
  _p('FP007', 'Koray Aldemir', 'Measured_Aggressor',
      vpip: 0.25, pfr: 0.19, threeBet: 0.10, gto: 0.9, exploit: 0.25,
      chars: [_pos(0.7), _geo(0.5)],
      desc: 'Measured, aggressive world champion.'),
  _p('FP008', 'Scott Seiver', 'Adaptive_Reg',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.85, exploit: 0.35, risk: 1.15,
      chars: [_soul(0.6), _geo(0.6), _pos(0.6)],
      desc: 'Sharp, adaptive, endlessly tough high-stakes reg.'),
  _p('FP009', 'Dario Sammartino', 'Creative_Aggressor',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.85, exploit: 0.35, risk: 1.2,
      chars: [_lev(0.6), _geo(0.6)],
      desc: 'Creative, aggressive Italian high-roller.'),
  _p('FP010', 'Brian Rast', 'Versatile_Pro',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.85, exploit: 0.35,
      chars: [_soul(0.6), _pos(0.6)],
      desc: 'Versatile and tough across every format.'),
  _p('FP011', 'Doug Polk', 'Heads_Up_Assassin',
      vpip: 0.30, pfr: 0.23, threeBet: 0.13, gto: 0.9, exploit: 0.4, risk: 1.3,
      chars: [_lev(0.8), _geo(0.7), _pos(0.6)],
      desc: 'Ruthless heads-up specialist; maximum pressure.'),
  _p('FP012', 'Phil Galfond', 'Deep_Thinker',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.9, exploit: 0.3, risk: 1.1,
      chars: [_geo(0.7), _pos(0.6)],
      desc: 'Deep-thinking PLO/NLHE great.'),
  _p('FP013', 'Nick Schulman', 'Sharp_Mixed',
      vpip: 0.25, pfr: 0.19, threeBet: 0.10, gto: 0.87, exploit: 0.35,
      chars: [_soul(0.6)],
      desc: 'Sharp mixed-game player and reader.'),
  _p('FP014', 'Benny Glaser', 'Mixed_Technician',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.9, exploit: 0.2,
      chars: [_pos(0.6)],
      desc: 'Mixed-game technician; disciplined.'),
  _p('FP015', 'Paul Sokolov', 'Modern_Reg',
      vpip: 0.28, pfr: 0.21, threeBet: 0.11, gto: 0.85, exploit: 0.3, risk: 1.1,
      chars: [_lev(0.5), _pos(0.6)],
      desc: 'Aggressive modern online-bred reg.'),

  // ---- Aggressive tournament crushers -------------------------------------
  _p('FP016', 'Michael Mizrachi', 'Aggressive_Grinder',
      vpip: 0.30, pfr: 0.23, threeBet: 0.13, gto: 0.8, exploit: 0.45, risk: 1.3,
      chars: [_lev(0.7), _geo(0.6)],
      desc: 'The Grinder — aggressive and fearless.'),
  _p('FP017', 'Ben Lamb', 'Aggressive_MTT',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.82, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.6), _geo(0.5)],
      desc: 'Aggressive tournament crusher.'),
  _p('FP018', 'Greg Merson', 'Disciplined_Aggressor',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.85, exploit: 0.3,
      chars: [_pos(0.6)],
      desc: 'Disciplined WSOP Main Event champion.'),
  _p('FP019', 'Ryan Riess', 'Young_Aggressor',
      vpip: 0.28, pfr: 0.21, threeBet: 0.11, gto: 0.8, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.6)],
      desc: 'Aggressive young champion.'),
  _p('FP020', 'Joe Cada', 'Aggressive_Champion',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.85, exploit: 0.35, risk: 1.15,
      chars: [_pos(0.6), _lev(0.5)],
      desc: 'Aggressive multi-bracelet winner.'),
  _p('FP021', 'Jonathan Duhamel', 'Aggressive_Champion',
      vpip: 0.28, pfr: 0.21, threeBet: 0.11, gto: 0.82, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.6)],
      desc: 'Aggressive Canadian champion.'),
  _p('FP022', 'Peter Eastgate', 'Calm_Solid',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.85, exploit: 0.3,
      chars: [_pos(0.6)],
      desc: 'Calm, solid Main Event champion.'),
  _p('FP023', 'John Racener', 'Steady_Pro',
      vpip: 0.25, pfr: 0.19, threeBet: 0.10, gto: 0.85, exploit: 0.3,
      desc: 'Steady, solid tournament pro.'),
  _p('FP024', 'Paul Wasicka', 'Composed_Pro',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.85, exploit: 0.3,
      desc: 'Composed final-table pro.'),
  _p('FP025', 'Joe Hachem', 'Personable_Aggressor',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.8, exploit: 0.35, risk: 1.1,
      chars: [_lev(0.5)],
      desc: 'Aggressive, personable champion.'),
  _p('FP026', 'Carlos Mortensen', 'The_Matador',
      vpip: 0.30, pfr: 0.22, threeBet: 0.12, gto: 0.78, exploit: 0.45, risk: 1.25,
      chars: [_lev(0.6), _soul(0.5)],
      desc: 'The Matador — aggressive and fearless.'),
  _p('FP027', 'Maurice Hawkins', 'High_Volume_Grinder',
      vpip: 0.30, pfr: 0.22, threeBet: 0.12, gto: 0.78, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.6)],
      desc: 'High-volume, aggressive ring-game grinder.'),
  _p('FP028', 'Josh Arieh', 'Talkative_Aggressor',
      vpip: 0.30, pfr: 0.22, threeBet: 0.12, gto: 0.78, exploit: 0.45, risk: 1.2,
      chars: [_lev(0.6), _soul(0.5)],
      desc: 'Aggressive, talkative live pro.'),
  _p('FP029', 'David Williams', 'Versatile_Aggressor',
      vpip: 0.28, pfr: 0.21, threeBet: 0.11, gto: 0.82, exploit: 0.35, risk: 1.15,
      chars: [_lev(0.5)],
      desc: 'Versatile, aggressive pro.'),
  _p('FP030', 'Ram Vaswani', 'Hendon_Aggressor',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.8, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.6)],
      desc: 'Aggressive Hendon Mob mainstay.'),
  _p('FP031', 'Tuan Le', 'Aggressive_Live',
      vpip: 0.30, pfr: 0.22, threeBet: 0.12, gto: 0.75, exploit: 0.5, risk: 1.2,
      chars: [_lev(0.6), _soul(0.5)],
      desc: 'Aggressive WPT-era live pro.'),

  // ---- LAG / hyper-aggressive ---------------------------------------------
  _p('FP032', 'Vanessa Selbst', 'Hyper_LAG',
      vpip: 0.33, pfr: 0.25, threeBet: 0.14, gto: 0.82, exploit: 0.5, risk: 1.4,
      chars: [_lev(0.8), _geo(0.7)],
      desc: 'Fearless, hyper-aggressive crusher.'),
  _p('FP033', 'Patrik Antonius', 'Balanced_LAG',
      vpip: 0.31, pfr: 0.23, threeBet: 0.13, gto: 0.85, exploit: 0.4, risk: 1.3,
      chars: [_lev(0.7), _geo(0.7)],
      desc: 'Balanced, aggressive high-stakes force.'),
  _p('FP034', 'David Benyamine', 'Cash_LAG',
      vpip: 0.32, pfr: 0.24, threeBet: 0.13, gto: 0.75, exploit: 0.5, risk: 1.35,
      chars: [_lev(0.7), _geo(0.6)],
      desc: 'Loose-aggressive cash-game force.'),
  _p('FP035', 'Bertrand Grospellier', 'ElkY',
      vpip: 0.31, pfr: 0.23, threeBet: 0.13, gto: 0.82, exploit: 0.4, risk: 1.3,
      chars: [_lev(0.7), _pos(0.6)],
      desc: 'ElkY — fast, aggressive, online-bred.'),
  _p('FP036', 'Eli Elezra', 'Action_Gambler',
      vpip: 0.31, pfr: 0.23, threeBet: 0.12, gto: 0.7, exploit: 0.5, risk: 1.3,
      chars: [_lev(0.7), _soul(0.5)],
      desc: 'Action-loving live gambler.'),
  _p('FP037', 'Qui Nguyen', 'Unpredictable_LAG',
      vpip: 0.34, pfr: 0.25, threeBet: 0.13, gto: 0.68, exploit: 0.55, risk: 1.35,
      tilt: 0.7, chars: [_lev(0.8), _soul(0.5)],
      desc: 'Fearless, unpredictable live LAG.'),
  _p('FP038', 'Mike Matusow', 'The_Mouth',
      vpip: 0.30, pfr: 0.22, threeBet: 0.12, gto: 0.72, exploit: 0.5, risk: 1.25,
      tilt: 0.35, chars: [_lev(0.7), _soul(0.5)],
      desc: 'The Mouth — aggressive and tilt-prone.'),
  _p('FP039', 'Stu Ungar', 'Instinctive_Genius',
      vpip: 0.32, pfr: 0.24, threeBet: 0.13, gto: 0.8, exploit: 0.55, risk: 1.3,
      oppRead: 0.95, chars: [_soul(0.9), _lev(0.7)],
      desc: 'The Kid — the greatest instinctive tournament genius.'),

  // ---- Old-school legends / feel players (reads-driven) --------------------
  _p('FP040', 'Phil Ivey', 'The_GOAT',
      vpip: 0.28, pfr: 0.21, threeBet: 0.11, gto: 0.85, exploit: 0.5, risk: 1.2,
      tilt: 0.99, oppRead: 0.98,
      chars: [_soul(0.95), _lev(0.6), _geo(0.6)],
      desc: 'The GOAT — flawless reads, relentless, fearless.'),
  _p('FP041', 'Doyle Brunson', 'The_Godfather',
      vpip: 0.30, pfr: 0.22, threeBet: 0.11, gto: 0.68, exploit: 0.55, risk: 1.2,
      oppRead: 0.9, chars: [_soul(0.8), _lev(0.6)],
      desc: 'The Godfather — aggressive, fearless pioneer.'),
  _p('FP042', 'Johnny Chan', 'Orient_Express',
      vpip: 0.27, pfr: 0.20, threeBet: 0.10, gto: 0.72, exploit: 0.55, oppRead: 0.9,
      chars: [_soul(0.85)],
      desc: 'Orient Express — masterful reads and timing.'),
  _p('FP043', 'Erik Seidel', 'Ageless_Legend',
      vpip: 0.25, pfr: 0.19, threeBet: 0.10, gto: 0.82, exploit: 0.4, oppRead: 0.85,
      chars: [_soul(0.8), _pos(0.6)],
      desc: 'Ageless, adaptive, disciplined legend.'),
  _p('FP044', 'Ted Forrest', 'Feel_Genius',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.75, exploit: 0.5, oppRead: 0.9,
      chars: [_soul(0.8)],
      desc: 'Feel-player genius with huge reads.'),
  _p('FP045', 'John Hennigan', 'Johnny_World',
      vpip: 0.27, pfr: 0.20, threeBet: 0.10, gto: 0.78, exploit: 0.45, oppRead: 0.8,
      chars: [_soul(0.6)],
      desc: 'Johnny World — fearless mixed-game action.'),
  _p('FP046', 'Antonio Esfandiari', 'The_Magician',
      vpip: 0.30, pfr: 0.22, threeBet: 0.11, gto: 0.72, exploit: 0.5, risk: 1.15,
      oppRead: 0.8, chars: [_soul(0.7), _lev(0.5)],
      desc: 'Charismatic, tricky live magician.'),
  _p('FP047', 'Scotty Nguyen', 'Prince_Of_Poker',
      vpip: 0.31, pfr: 0.23, threeBet: 0.12, gto: 0.7, exploit: 0.55, risk: 1.2,
      oppRead: 0.8, chars: [_soul(0.7), _lev(0.6)],
      desc: 'Prince of Poker — tricky and aggressive.'),
  _p('FP048', 'Barry Greenstein', 'Robin_Hood',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.8, exploit: 0.4, oppRead: 0.8,
      chars: [_soul(0.6)],
      desc: 'Robin Hood of Poker — disciplined, analytical.'),
  _p('FP049', 'Howard Lederer', 'The_Professor',
      vpip: 0.22, pfr: 0.16, threeBet: 0.08, gto: 0.82, exploit: 0.4, oppRead: 0.75,
      chars: [_soul(0.6), _pos(0.6)],
      desc: 'The Professor — patient and cerebral.'),
  _p('FP050', 'Todd Brunson', 'Big_Game_Cash',
      vpip: 0.27, pfr: 0.20, threeBet: 0.10, gto: 0.75, exploit: 0.5, oppRead: 0.8,
      chars: [_soul(0.6)],
      desc: 'Big-game cash specialist.'),
  _p('FP051', 'Bobby Baldwin', 'Cerebral_Champion',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.78, exploit: 0.4, oppRead: 0.75,
      chars: [_soul(0.6)],
      desc: 'Cerebral old-school champion.'),
  _p('FP052', 'Mike Sexton', 'The_Ambassador',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.78, exploit: 0.4, oppRead: 0.75,
      chars: [_soul(0.6)],
      desc: 'Ambassador of the game — solid and tricky.'),
  _p('FP053', 'Gabe Kaplan', 'Old_School_Sharp',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.72, exploit: 0.5, oppRead: 0.8,
      chars: [_soul(0.6)],
      desc: 'Sharp old-school live player.'),
  _p('FP054', 'Huck Seed', 'Unorthodox_AllRounder',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.78, exploit: 0.4, oppRead: 0.7,
      chars: [_soul(0.6)],
      desc: 'Unorthodox, tough all-arounder.'),
  _p('FP055', 'Allen Cunningham', 'Smooth_Positional',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.82, exploit: 0.35, oppRead: 0.75,
      chars: [_soul(0.6), _pos(0.6)],
      desc: 'Smooth, respected, positionally sound.'),
  _p('FP056', 'John Cernuto', 'Seasoned_Vet',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.75, exploit: 0.4, oppRead: 0.7,
      chars: [_soul(0.5)],
      desc: 'Miami John — seasoned veteran.'),

  // ---- Thinking / analytical pros ------------------------------------------
  _p('FP058', 'Jennifer Harman', 'Elite_Cash',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.85, exploit: 0.4, oppRead: 0.85,
      chars: [_soul(0.7)],
      desc: 'Elite high-stakes cash pro.'),
  _p('FP059', 'Annie Duke', 'Decision_Theorist',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.78, exploit: 0.45, oppRead: 0.85,
      chars: [_soul(0.7)],
      desc: 'Decision-theorist; sharp reads.'),
  _p('FP060', 'Kathy Liebert', 'Steady_Veteran',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.8, exploit: 0.35, oppRead: 0.7,
      chars: [_soul(0.5)],
      desc: 'Steady, aggressive veteran.'),
  _p('FP061', 'Jennifer Tilly', 'Action_Loving',
      vpip: 0.33, pfr: 0.24, threeBet: 0.12, gto: 0.68, exploit: 0.45, risk: 1.2,
      tilt: 0.7, chars: [_lev(0.6), _soul(0.4)],
      desc: 'Loose, fearless, action-loving.'),
  _p('FP062', 'Cyndy Violette', 'Disciplined_Solid',
      vpip: 0.22, pfr: 0.16, threeBet: 0.08, gto: 0.82, exploit: 0.3,
      desc: 'Disciplined, solid pro.'),

  // ---- Tight / nitty / mathematical ---------------------------------------
  _p('FP063', 'Allen Kessler', 'Chainsaw_Nit',
      vpip: 0.18, pfr: 0.12, threeBet: 0.04, gto: 0.8, exploit: 0.2, tilt: 0.7,
      desc: 'Chainsaw — famously tight and value-driven.'),
  _p('FP064', 'Chris Ferguson', 'Jesus_GTO',
      vpip: 0.22, pfr: 0.16, threeBet: 0.08, gto: 0.95, exploit: 0.1,
      chars: [_pos(0.6)],
      desc: 'Jesus — mathematical and disciplined.'),
  _p('FP065', 'Jeff Lisandro', 'Mixed_Specialist',
      vpip: 0.20, pfr: 0.14, threeBet: 0.06, gto: 0.82, exploit: 0.3,
      chars: [_soul(0.6)],
      desc: 'Disciplined mixed-game specialist.'),
  _p('FP066', 'Tom McEvoy', 'ABC_Champion',
      vpip: 0.20, pfr: 0.14, threeBet: 0.06, gto: 0.8, exploit: 0.25,
      desc: 'Conservative ABC champion.'),
  _p('FP067', 'Greg Raymer', 'Fossilman',
      vpip: 0.22, pfr: 0.16, threeBet: 0.08, gto: 0.82, exploit: 0.35,
      chars: [_soul(0.5)],
      desc: 'Fossilman — analytical and solid.'),

  // ---- Special ------------------------------------------------------------
  _p('FP068', 'Bing Diao', 'Analytical_Machine',
      vpip: 0.23, pfr: 0.17, threeBet: 0.09, gto: 0.95, exploit: 0.15, tilt: 0.97,
      oppRead: 0.6, chars: [_pos(0.85), _geo(0.5)],
      desc: 'Hyper-analytical, patient, near-unexploitable technician.'),

  // ---- Modern GTO high-rollers / solver-era regs --------------------------
  _p('FP069', 'Danny Tang', 'GTO_High_Roller',
      vpip: 0.25, pfr: 0.19, threeBet: 0.11, gto: 0.92, exploit: 0.2, risk: 1.1,
      chars: [_geo(0.6), _pos(0.7)],
      desc: 'Studious Hong Kong high-roller regular.'),
  _p('FP070', 'Paul Phua', 'Aggressive_Whale',
      vpip: 0.32, pfr: 0.20, threeBet: 0.10, gto: 0.72, exploit: 0.5, risk: 1.3,
      tilt: 0.6, chars: [_lev(0.6), _soul(0.5)],
      desc: 'Loose, fearless super-high-roller businessman.'),
  _p('FP071', 'Nacho Barbero', 'LAG_Grinder',
      vpip: 0.31, pfr: 0.23, threeBet: 0.13, gto: 0.82, exploit: 0.4, risk: 1.25,
      chars: [_lev(0.6), _pos(0.6)],
      desc: 'Aggressive, high-volume Argentine grinder.'),
  _p('FP072', 'Christoph Vogelsang', 'GTO_Technician',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.96, exploit: 0.1,
      chars: [_geo(0.6), _pos(0.7)],
      desc: 'Quiet, near-unexploitable super-high-roller.'),
  _p('FP073', 'Elton Tsang', 'Aggressive_Whale',
      vpip: 0.31, pfr: 0.21, threeBet: 0.11, gto: 0.75, exploit: 0.45, risk: 1.3,
      tilt: 0.7, chars: [_lev(0.6)],
      desc: 'Big-game gambler with a huge aggressive streak.'),
  _p('FP074', 'Seth Davies', 'GTO_High_Roller',
      vpip: 0.26, pfr: 0.20, threeBet: 0.12, gto: 0.92, exploit: 0.25, risk: 1.15,
      chars: [_geo(0.6), _pos(0.7)],
      desc: 'Modern solver-era high-roller crusher.'),
  _p('FP075', 'Tan Xuan', 'Aggressive_High_Roller',
      vpip: 0.29, pfr: 0.21, threeBet: 0.12, gto: 0.82, exploit: 0.4, risk: 1.25,
      chars: [_lev(0.6), _geo(0.5)],
      desc: 'Aggressive Asian super-high-roller regular.'),
  _p('FP076', 'Daniel Cates', 'Unorthodox_Genius',
      vpip: 0.30, pfr: 0.22, threeBet: 0.13, gto: 0.85, exploit: 0.5, risk: 1.3,
      oppRead: 0.85, chars: [_soul(0.7), _lev(0.7), _geo(0.6)],
      desc: 'Jungleman — creative, exploitative online legend.'),
  _p('FP077', 'Eric Persson', 'Action_Whale',
      vpip: 0.34, pfr: 0.24, threeBet: 0.12, gto: 0.65, exploit: 0.55, risk: 1.4,
      tilt: 0.4, chars: [_lev(0.7), _soul(0.4)],
      desc: 'Maverick action-junkie; maximum gamble.'),
  _p('FP078', 'Wang Ye', 'Aggressive_Live',
      vpip: 0.30, pfr: 0.21, threeBet: 0.11, gto: 0.76, exploit: 0.45, risk: 1.2,
      chars: [_lev(0.6)],
      desc: 'Aggressive Chinese high-stakes live player.'),
  _p('FP079', 'Chris Brewer', 'GTO_High_Roller',
      vpip: 0.26, pfr: 0.20, threeBet: 0.12, gto: 0.93, exploit: 0.22, risk: 1.15,
      chars: [_geo(0.7), _pos(0.7)],
      desc: 'Dominant modern super-high-roller technician.'),
  _p('FP080', 'Sean Winter', 'Aggressive_High_Roller',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.85, exploit: 0.35, risk: 1.25,
      chars: [_lev(0.6), _geo(0.6)],
      desc: 'Fearless, aggressive high-roller regular.'),
  _p('FP081', 'Brian Kim', 'GTO_Reg',
      vpip: 0.25, pfr: 0.19, threeBet: 0.11, gto: 0.9, exploit: 0.25,
      chars: [_pos(0.6)],
      desc: 'Solid, disciplined high-roller regular.'),
  _p('FP082', 'Nick Petrangelo', 'GTO_Technician',
      vpip: 0.25, pfr: 0.19, threeBet: 0.11, gto: 0.94, exploit: 0.15,
      chars: [_geo(0.6), _pos(0.7)],
      desc: 'Coach-sharp, near-unexploitable technician.'),
  _p('FP083', 'Espen Jorstad', 'Balanced_Aggressor',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.9, exploit: 0.3, risk: 1.15,
      chars: [_pos(0.7), _lev(0.5)],
      desc: 'Balanced, aggressive Main Event champion.'),
  _p('FP084', 'Xu Liang', 'Aggressive_Live',
      vpip: 0.29, pfr: 0.21, threeBet: 0.11, gto: 0.76, exploit: 0.45, risk: 1.2,
      chars: [_lev(0.6)],
      desc: 'Aggressive Asian tournament crusher.'),
  _p('FP085', 'Brandon Wilson', 'Aggressive_High_Roller',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.84, exploit: 0.4, risk: 1.25,
      chars: [_lev(0.6)],
      desc: 'Aggressive high-roller cash and tournament player.'),
  _p('FP086', 'David Yan', 'GTO_Technician',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.94, exploit: 0.18,
      chars: [_geo(0.6), _pos(0.7)],
      desc: 'Studious, precise New Zealand technician.'),
  _p('FP087', 'Sosia Jiang', 'Aggressive_High_Roller',
      vpip: 0.28, pfr: 0.20, threeBet: 0.11, gto: 0.82, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive, ambitious high-roller regular.'),
  _p('FP088', 'Luc Greenwood', 'GTO_High_Roller',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.92, exploit: 0.25, risk: 1.1,
      chars: [_pos(0.7), _geo(0.5)],
      desc: 'Disciplined member of the Greenwood high-roller family.'),

  // ---- Grinders, coaches, and mixed reputations ---------------------------
  _p('FP089', 'Chris Moneymaker', 'Aggressive_Amateur',
      vpip: 0.31, pfr: 0.21, threeBet: 0.10, gto: 0.7, exploit: 0.45, risk: 1.2,
      tilt: 0.6, chars: [_lev(0.5), _soul(0.4)],
      desc: 'The poker-boom everyman; loose and fearless.'),
  _p('FP090', 'Ebony Kenney', 'Solid_Reg',
      vpip: 0.25, pfr: 0.19, threeBet: 0.10, gto: 0.87, exploit: 0.35,
      chars: [_pos(0.6)],
      desc: 'Solid, well-studied modern tournament reg.'),
  _p('FP091', 'Aleksandr Zubov', 'Aggressive_Reg',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.83, exploit: 0.35, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive Russian high-stakes regular.'),
  _p('FP092', 'Dylan Weisman', 'GTO_Reg',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.9, exploit: 0.3, risk: 1.1,
      chars: [_pos(0.6)],
      desc: 'Studious, aggressive high-roller regular.'),
  _p('FP093', 'Calvin Lee', 'Solid_Grinder',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.85, exploit: 0.35,
      desc: 'Steady, well-rounded tournament grinder.'),
  _p('FP094', 'Bill Perkins', 'Action_Whale',
      vpip: 0.33, pfr: 0.22, threeBet: 0.11, gto: 0.66, exploit: 0.5, risk: 1.4,
      tilt: 0.5, chars: [_lev(0.6), _soul(0.4)],
      desc: 'High-stakes gambler who loves the action.'),
  _p('FP095', 'Shaun Deeb', 'Exploitative_Grinder',
      vpip: 0.30, pfr: 0.22, threeBet: 0.13, gto: 0.8, exploit: 0.55, risk: 1.25,
      oppRead: 0.8, chars: [_lev(0.6), _soul(0.6)],
      desc: 'Relentless, exploit-heavy high-volume grinder.'),
  _p('FP096', 'Naoya Kihara', 'Solid_Technician',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.9, exploit: 0.25,
      chars: [_pos(0.6)],
      desc: 'Disciplined, studious Japanese pro.'),
  _p('FP097', 'Jesse Lonis', 'Aggressive_High_Roller',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.85, exploit: 0.4, risk: 1.25,
      chars: [_lev(0.6), _geo(0.5)],
      desc: 'Aggressive, rising high-roller crusher.'),
  _p('FP098', 'Michael Moncek', 'Solid_Reg',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.86, exploit: 0.35,
      desc: 'Solid, consistent tournament regular.'),
  _p('FP099', 'Joshua Reichard', 'Aggressive_Grinder',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.8, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive, prolific high-stakes tournament winner.'),
  _p('FP100', 'Calvin Anderson', 'Mixed_Grinder',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.88, exploit: 0.35,
      chars: [_pos(0.6)],
      desc: 'Versatile, disciplined mixed-game grinder.'),
  _p('FP101', 'Martin Zamani', 'Aggressive_LAG',
      vpip: 0.31, pfr: 0.23, threeBet: 0.13, gto: 0.78, exploit: 0.45, risk: 1.3,
      tilt: 0.65, chars: [_lev(0.6)],
      desc: 'Fiery, aggressive tournament LAG.'),
  _p('FP102', 'Lucas Jumalon', 'Solid_Reg',
      vpip: 0.26, pfr: 0.19, threeBet: 0.11, gto: 0.87, exploit: 0.35,
      desc: 'Steady, well-studied tournament regular.'),
  _p('FP103', 'Myles Mullaly', 'Aggressive_Reg',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.84, exploit: 0.35, risk: 1.15,
      chars: [_lev(0.5)],
      desc: 'Aggressive, modern high-roller regular.'),
  _p('FP104', 'Marco Johnson', 'Solid_Veteran',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.84, exploit: 0.35,
      desc: 'Consistent, solid tournament veteran.'),
  _p('FP105', 'Nicholas Pupillo', 'Aggressive_Grinder',
      vpip: 0.29, pfr: 0.21, threeBet: 0.11, gto: 0.79, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive high-volume tournament grinder.'),
  _p('FP106', 'Ren Lin', 'Aggressive_High_Roller',
      vpip: 0.28, pfr: 0.20, threeBet: 0.11, gto: 0.82, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive high-roller tournament crusher.'),
  _p('FP107', 'Jamie Dwan', 'Solid_Reg',
      vpip: 0.26, pfr: 0.19, threeBet: 0.11, gto: 0.85, exploit: 0.35,
      chars: [_pos(0.6)],
      desc: 'Solid, aggressive European tournament reg.'),
  _p('FP108', 'Marius Kudzmanas', 'Aggressive_Reg',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.82, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive online-bred high-stakes reg.'),
  _p('FP109', 'Antonio Vargas', 'Aggressive_MTT',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.83, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5), _pos(0.6)],
      desc: 'Aggressive, talented young tournament crusher.'),
  _p('FP110', 'Martin Kabrhel', 'Chaotic_Whale',
      vpip: 0.34, pfr: 0.24, threeBet: 0.13, gto: 0.68, exploit: 0.55, risk: 1.4,
      tilt: 0.4, oppRead: 0.7, chars: [_lev(0.8), _soul(0.5)],
      desc: 'Wild, table-talking, chaotic high-roller.'),
  _p('FP111', 'Punnat Punsri', 'Solid_Reg',
      vpip: 0.26, pfr: 0.19, threeBet: 0.11, gto: 0.87, exploit: 0.3,
      chars: [_pos(0.6)],
      desc: 'Studious, disciplined Thai tournament reg.'),
  _p('FP112', 'Matthew Vengrin', 'Aggressive_Grinder',
      vpip: 0.28, pfr: 0.21, threeBet: 0.11, gto: 0.8, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive high-volume tournament grinder.'),
  _p('FP113', 'Christopher Nguyen', 'Aggressive_Reg',
      vpip: 0.28, pfr: 0.20, threeBet: 0.11, gto: 0.8, exploit: 0.4, risk: 1.15,
      chars: [_lev(0.5)],
      desc: 'Aggressive, well-rounded tournament regular.'),
  _p('FP114', 'Jonathan Little', 'Coach_Solid',
      vpip: 0.26, pfr: 0.20, threeBet: 0.11, gto: 0.9, exploit: 0.4, oppRead: 0.75,
      chars: [_pos(0.6), _soul(0.5)],
      desc: 'Prolific coach; solid, teaching-clean fundamentals.'),
  _p('FP115', 'Jonathan Turner', 'Aggressive_Reg',
      vpip: 0.28, pfr: 0.21, threeBet: 0.12, gto: 0.82, exploit: 0.4, risk: 1.15,
      chars: [_lev(0.5)],
      desc: 'Aggressive, adaptable tournament regular.'),
  _p('FP116', 'Jeffrey Madsen', 'Solid_Veteran',
      vpip: 0.25, pfr: 0.19, threeBet: 0.10, gto: 0.84, exploit: 0.35,
      desc: 'Young-champion-turned-steady veteran.'),
  _p('FP117', 'Lauri Saaskilahti', 'Aggressive_Reg',
      vpip: 0.29, pfr: 0.22, threeBet: 0.12, gto: 0.83, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5), _pos(0.6)],
      desc: 'Aggressive Finnish online-bred regular.'),

  // ---- Content creators / streamers / personalities -----------------------
  _p('FP118', 'Liv Boeree', 'Analytical_Solid',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.85, exploit: 0.35, oppRead: 0.7,
      chars: [_soul(0.5), _pos(0.6)],
      desc: 'Analytical, science-minded solid pro.'),
  _p('FP119', 'Loni Hui', 'Aggressive_Reg',
      vpip: 0.28, pfr: 0.20, threeBet: 0.11, gto: 0.82, exploit: 0.4, risk: 1.15,
      chars: [_lev(0.5)],
      desc: 'Aggressive, sharp tournament regular.'),
  _p('FP120', 'Andrew Neeme', 'Solid_Live',
      vpip: 0.27, pfr: 0.19, threeBet: 0.10, gto: 0.8, exploit: 0.4, oppRead: 0.7,
      chars: [_soul(0.5)],
      desc: 'Vlog-era live cash grinder; patient and solid.'),
  _p('FP121', 'Mariano Grandoli', 'Aggressive_Live',
      vpip: 0.30, pfr: 0.21, threeBet: 0.11, gto: 0.76, exploit: 0.45, risk: 1.2,
      tilt: 0.7, chars: [_lev(0.5), _soul(0.4)],
      desc: 'High-stakes cash streamer; loose and aggressive.'),
  _p('FP122', 'Corey Eyring', 'Solid_Live',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.82, exploit: 0.4,
      chars: [_soul(0.4)],
      desc: 'Steady live cash-game vlogger and grinder.'),
  _p('FP123', 'Ryan DePaulo', 'Recreational_LAG',
      vpip: 0.32, pfr: 0.21, threeBet: 0.10, gto: 0.68, exploit: 0.45, risk: 1.25,
      tilt: 0.55, chars: [_lev(0.5), _soul(0.4)],
      desc: 'Degenerate-brand vlogger; loose and fearless.'),
  _p('FP124', 'David Kaye', 'Solid_Live',
      vpip: 0.27, pfr: 0.19, threeBet: 0.10, gto: 0.8, exploit: 0.4,
      chars: [_soul(0.4)],
      desc: 'Live cash content creator; solid fundamentals.'),
  _p('FP125', 'Bart Hanson', 'Coach_Exploit',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.82, exploit: 0.5, oppRead: 0.8,
      chars: [_soul(0.6), _pos(0.6)],
      desc: 'Live-cash coach; exploit-heavy, reads-driven.'),
  _p('FP126', 'James Sweeney', 'Solid_Live',
      vpip: 0.27, pfr: 0.19, threeBet: 0.10, gto: 0.8, exploit: 0.4,
      chars: [_soul(0.4)],
      desc: 'Live cash grinder and content creator.'),
  _p('FP127', 'Alec Torelli', 'Balanced_Live',
      vpip: 0.27, pfr: 0.20, threeBet: 0.11, gto: 0.83, exploit: 0.4, oppRead: 0.7,
      chars: [_soul(0.5), _pos(0.6)],
      desc: 'Balanced live pro and coach.'),
  _p('FP128', 'Kevin Martin', 'Aggressive_Stream',
      vpip: 0.29, pfr: 0.21, threeBet: 0.11, gto: 0.8, exploit: 0.4, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive tournament streamer.'),
  _p('FP129', 'Marc Goone', 'Aggressive_Content',
      vpip: 0.30, pfr: 0.21, threeBet: 0.11, gto: 0.76, exploit: 0.45, risk: 1.25,
      chars: [_lev(0.5), _soul(0.4)],
      desc: 'Aggressive content-creator and cash player.'),
  _p('FP130', 'Nathan Williams', 'Coach_Nit',
      vpip: 0.22, pfr: 0.15, threeBet: 0.06, gto: 0.88, exploit: 0.4, oppRead: 0.7,
      chars: [_pos(0.6)],
      desc: 'BlackRain79 — tight-aggressive micro-stakes coach.'),
  _p('FP131', 'Lex Veldhuis', 'Aggressive_Stream',
      vpip: 0.30, pfr: 0.22, threeBet: 0.12, gto: 0.8, exploit: 0.4, risk: 1.25,
      tilt: 0.7, chars: [_lev(0.6)],
      desc: 'Beloved aggressive tournament streamer.'),
  _p('FP132', 'Matt Berkey', 'Exploit_Cash',
      vpip: 0.28, pfr: 0.20, threeBet: 0.11, gto: 0.83, exploit: 0.55, risk: 1.2,
      oppRead: 0.85, chars: [_soul(0.7), _lev(0.6)],
      desc: 'High-stakes cash exploiter and coach.'),
  _p('FP133', 'Will Kassouf', 'Speech_Play_LAG',
      vpip: 0.32, pfr: 0.21, threeBet: 0.11, gto: 0.7, exploit: 0.5, risk: 1.25,
      tilt: 0.6, oppRead: 0.75, chars: [_soul(0.6), _lev(0.6)],
      desc: 'Speech-play specialist; loose, needling, aggressive.'),
  _p('FP134', 'Abby Merk', 'Solid_Reg',
      vpip: 0.26, pfr: 0.19, threeBet: 0.11, gto: 0.85, exploit: 0.35,
      chars: [_pos(0.6)],
      desc: 'Studious, solid tournament regular and creator.'),
  _p('FP135', 'Alexander Wolfgang', 'Solid_Live',
      vpip: 0.27, pfr: 0.19, threeBet: 0.10, gto: 0.8, exploit: 0.4,
      chars: [_soul(0.4)],
      desc: 'Live cash grinder and content creator.'),
  _p('FP136', 'Gregory Liow', 'Aggressive_Reg',
      vpip: 0.28, pfr: 0.20, threeBet: 0.11, gto: 0.82, exploit: 0.4, risk: 1.15,
      chars: [_lev(0.5)],
      desc: 'Aggressive Southeast-Asian tournament reg.'),
  _p('FP137', 'Frank Cucchiara', 'Solid_Live',
      vpip: 0.26, pfr: 0.19, threeBet: 0.10, gto: 0.8, exploit: 0.4,
      chars: [_soul(0.4)],
      desc: 'Live cash player and content creator.'),
  _p('FP138', 'Kitty Kuo', 'Aggressive_Live',
      vpip: 0.30, pfr: 0.21, threeBet: 0.11, gto: 0.75, exploit: 0.45, risk: 1.2,
      tilt: 0.65, chars: [_lev(0.5), _soul(0.4)],
      desc: 'Aggressive, fearless Taiwanese live pro.'),
  _p('FP139', 'Han Feng', 'Aggressive_Live',
      vpip: 0.29, pfr: 0.21, threeBet: 0.11, gto: 0.77, exploit: 0.45, risk: 1.2,
      chars: [_lev(0.5)],
      desc: 'Aggressive Asian high-stakes tournament player.'),
  _p('FP140', 'Andreas Wagner', 'Solid_Reg',
      vpip: 0.25, pfr: 0.18, threeBet: 0.10, gto: 0.85, exploit: 0.35,
      desc: 'Steady, disciplined European tournament reg.'),
  _p('FP141', 'Victoria Coren', 'Composed_Solid',
      vpip: 0.24, pfr: 0.18, threeBet: 0.10, gto: 0.82, exploit: 0.4, oppRead: 0.75,
      chars: [_soul(0.5)],
      desc: 'Composed, sharp two-time EPT champion.'),
];
