import 'package:monte/core/domain/ai/custom_players.dart';
import 'package:monte/core/domain/ai/player_profile.dart';
import 'package:monte/core/domain/engine/game.dart';

/// Built-in seed profiles from `docs/personality-model.md` (the Master Archetype
/// Catalog). These are the verified profiles used to seed evaluation tables,
/// plus any owner-created pros (generated by `tool/create_player.dart`).
final List<PlayerProfile> builtInProfiles = [
  danielNegreanu,
  michaelAddamo,
  isaacHaxton,
  bradOwen,
  ...customPros,
];

/// Profile A — The Small-Ball Hand Reader.
///
/// Plays a wide, controlled-aggression small-ball game: loose VPIP with modest
/// sizing (low `riskPremiumCoefficient`), leaning on reads rather than raw GTO
/// (low `gtoAdherenceWeight`, high `exploitativeWeight` + opponent-history
/// weight) to apply calculated pressure — and shifting gears to aggressive when
/// he has an edge in position (the `Soul_Read` trigger). Modelled on Daniel
/// Negreanu's game.
const danielNegreanu = PlayerProfile(
  id: 'P047',
  name: 'Daniel Negreanu',
  archetype: 'Small_Ball_Hand_Reader',
  // Pro-tier execution. skill must stay 1.0 — below it flips to the amateur
  // brain; ability differences vs other pros live in gtoAdherence / reads.
  skill: 1.0,
  strategicBaseline: StrategicBaseline(
    vpipTarget: 0.27,
    pfrTarget: 0.21,
    threeBetFrequency: 0.10,
    gtoAdherenceWeight: 0.70,
  ),
  behavioralModifiers: BehavioralModifiers(
    tiltResistance: 0.85,
    exploitativeWeight: 0.75,
    riskPremiumCoefficient: 0.90,
    // Extremely accurate hand reads: leans hard on observed opponent history.
    weightOnOpponentHistory: 0.90,
  ),
  engineTriggers: EngineTriggers(
    // "Switch to aggressive when warranted": armed in position from the flop on,
    // the read-based gear shift ramps postflop aggression.
    customMechanic: 'Soul_Read',
    condition: TriggerCondition(
      inPosition: true,
      minStreet: BettingRound.flop,
    ),
    actionModifier: ActionModifier(
      postflopAggressionMultiplierIp: 1.30,
    ),
  ),
  // Active representation of the trigger above (elite hand reader): drives the
  // ProfilePostflopPolicy soul-read mechanic — sharper ranging, deeper runouts,
  // in-position pressure.
  characteristics: [
    PlayerCharacteristic(id: 'Soul_Read', proficiency: 0.9),
  ],
);

/// Profile B — The Geometric Overbet Maximizer.
const michaelAddamo = PlayerProfile(
  id: 'P041',
  name: 'Michael Addamo',
  archetype: 'Hyper_Aggressive_Elite',
  // Top-tier aggressor — flawless execution.
  skill: 1.00,
  strategicBaseline: StrategicBaseline(
    vpipTarget: 0.30,
    pfrTarget: 0.26,
    threeBetFrequency: 0.13,
    gtoAdherenceWeight: 0.85,
  ),
  behavioralModifiers: BehavioralModifiers(
    tiltResistance: 0.99,
    exploitativeWeight: 0.60,
    riskPremiumCoefficient: 1.50,
    weightOnOpponentHistory: 0.50,
  ),
  engineTriggers: EngineTriggers(
    customMechanic: 'Geometric_Overbet_Execution',
    condition: TriggerCondition(
      minStreet: BettingRound.turn,
      hasNutAdvantage: true,
    ),
    actionModifier: ActionModifier(betSizeMultiplierFlopTurnRiver: 2.50),
  ),
  // Active representation of the trigger above: drives the geometric-overbet
  // mechanic (overbets later streets with a nut advantage).
  characteristics: [
    PlayerCharacteristic(id: 'Geometric_Overbet_Execution', proficiency: 0.9),
  ],
);

/// Profile C — The Pure GTO Anchor.
const isaacHaxton = PlayerProfile(
  id: 'P001',
  name: 'Isaac Haxton',
  archetype: 'GTO_Wizard',
  // The benchmark: flawless, unexploitable execution.
  skill: 1.00,
  strategicBaseline: StrategicBaseline(
    vpipTarget: 0.24,
    pfrTarget: 0.20,
    threeBetFrequency: 0.09,
    gtoAdherenceWeight: 1.00,
  ),
  behavioralModifiers: BehavioralModifiers(
    tiltResistance: 1.00,
    exploitativeWeight: 0.00,
    riskPremiumCoefficient: 1.00,
    weightOnOpponentHistory: 0.00,
  ),
);

/// Profile C — The exploitive pro.
const bradOwen = PlayerProfile(
  id: 'P002',
  name: 'Brad Owen',
  archetype: 'Exploitive_Pro',
  // Pro-tier execution (skill 1.0). His edge is exploitative reads + a lower GTO
  // adherence, not a degraded brain.
  skill: 1.0,
  strategicBaseline: StrategicBaseline(
    vpipTarget: 0.28,
    pfrTarget: 0.20,
    threeBetFrequency: 0.09,
    gtoAdherenceWeight: 0.68,
  ),
  behavioralModifiers: BehavioralModifiers(
    tiltResistance: 0.85,
    exploitativeWeight: 0.50,
    riskPremiumCoefficient: 1.15,
    weightOnOpponentHistory: 0.25,
  ),
  engineTriggers: EngineTriggers(
    // "Switch to aggressive when warranted": armed in position from the flop on,
    // the read-based gear shift ramps postflop aggression.
    customMechanic: 'Soul_Read',
    condition: TriggerCondition(
      inPosition: true,
      minStreet: BettingRound.flop,
    ),
    actionModifier: ActionModifier(
      postflopAggressionMultiplierIp: 1.20,
    ),
  ),
  // Active representation of the trigger above (exploitative reads): drives the
  // soul-read mechanic at a notch below Negreanu.
  characteristics: [
    PlayerCharacteristic(id: 'Soul_Read', proficiency: 0.7),
  ],
);
