import 'package:monte/core/domain/ai/player_profile.dart';

/// Emits the generated `custom_players.dart` source for the given owner-created
/// [recs] and [pros]. Each profile is rendered as `PlayerProfile.fromJson({...})`
/// off its own [PlayerProfile.toJson], so the round-trip is correct by
/// construction and there's no hand-written constructor to keep in sync.
///
/// Pure and deterministic (kept out of the interactive script so it's testable).
String customPlayersDartFile({
  required List<PlayerProfile> recs,
  required List<PlayerProfile> pros,
}) {
  final b = StringBuffer()
    ..writeln('// GENERATED — do not edit by hand.')
    ..writeln('//')
    ..writeln('// Regenerated by tool/create_player.dart whenever a player is '
        'created. Holds the')
    ..writeln('// owner-authored players, spread into homeGameProfiles / '
        'builtInProfiles.')
    ..writeln("import 'package:monte/core/domain/ai/player_profile.dart';")
    ..writeln()
    ..writeln('/// Owner-created recreational players (appended to the home-game '
        'roster).')
    ..writeln('final List<PlayerProfile> customRecreationalPlayers = '
        '<PlayerProfile>[');
  for (final p in recs) {
    b.writeln('  PlayerProfile.fromJson(${dartLiteral(p.toJson())}),');
  }
  b
    ..writeln('];')
    ..writeln()
    ..writeln('/// Owner-created pros (appended to the built-in pro roster).')
    ..writeln('final List<PlayerProfile> customPros = <PlayerProfile>[');
  for (final p in pros) {
    b.writeln('  PlayerProfile.fromJson(${dartLiteral(p.toJson())}),');
  }
  b.writeln('];');
  return b.toString();
}

/// Renders a JSON-ish value ([Map]/[List]/[String]/[num]/[bool]/null) as a Dart
/// literal. Strings are escaped for single-quoted Dart string syntax.
String dartLiteral(Object? v) {
  if (v == null) return 'null';
  if (v is bool || v is num) return '$v';
  if (v is String) return "'${_escape(v)}'";
  if (v is List) return '[${v.map(dartLiteral).join(', ')}]';
  if (v is Map) {
    final entries = v.entries
        .map((e) => '${dartLiteral(e.key)}: ${dartLiteral(e.value)}')
        .join(', ');
    return '{$entries}';
  }
  throw ArgumentError('Cannot render ${v.runtimeType} as a Dart literal.');
}

String _escape(String s) => s
    .replaceAll(r'\', r'\\')
    .replaceAll(r'$', r'\$')
    .replaceAll("'", r"\'")
    .replaceAll('\n', r'\n')
    .replaceAll('\r', r'\r');
