import 'dart:math';

import 'package:monte/core/domain/ai/player_profile.dart';
import 'package:monte/core/domain/ai/preflop_ranges.dart';
import 'package:monte/core/domain/ai/profile_policy.dart';
import 'package:monte/core/domain/engine/actions.dart';
import 'package:monte/core/domain/engine/bot.dart';
import 'package:monte/core/domain/engine/decision_policy.dart';
import 'package:monte/core/domain/engine/deck.dart';
import 'package:monte/core/domain/engine/game.dart';
import 'package:monte/core/domain/engine/player.dart';

/// Phase 1b: closed-loop calibration of a profile's preflop thresholds.
///
/// VPIP is a clean per-hand threshold, but PFR and 3-bet are
/// position-dependent — a PFR-range hand that faces a raise (and isn't a 3-bet)
/// flats instead of raising, so the open range must be *widened* to compensate.
/// The compensation depends on how often you face a raise (table dynamics), so
/// we measure it: simulate the profile against itself, compare measured vs target
/// frequencies, nudge the admitted fractions proportionally, and repeat to
/// convergence.
///
/// Pure engine (no UI / repository), so it stays Kotlin-portable.
class ProfileCalibrator {
  const ProfileCalibrator({
    this.playerCount = 6,
    this.iterations = 8,
    this.handsPerIteration = 5000,
    this.seed = 1,
  });

  final int playerCount;
  final int iterations;
  final int handsPerIteration;
  final int seed;

  static const _startingStack = 1000;

  /// Pre-baked calibrations for every shipped pro (generated by
  /// `tool/bake_calibration_cache.dart`), so seating any of them is instant
  /// instead of paying ~1.5s of live simulation at seat-creation time — with a
  /// tournament field seating dozens of named pros at once, that used to be
  /// several seconds of synchronous blocking on the UI thread before the
  /// first hand could be dealt. Keyed by `vpip_pfr_threeBet_playerCount`, not
  /// by name, so any two profiles sharing preflop targets share an entry.
  /// Re-run the generator and replace this block whenever the strength model
  /// changes; `test/ai/profile_calibration_test.dart` guards that calibrated
  /// profiles still hit their targets.
  static final Map<String, PreflopRanges> _cache = {
    '0.27_0.21_0.1_6': const PreflopRanges(
      vpip: 0.2709,
      pfr: 0.5650999999999999,
      threeBet: 0.5650999999999999,
    ), // Daniel Negreanu
    '0.32_0.26_0.13_6': const PreflopRanges(
      vpip: 0.2429,
      pfr: 0.5429999999999999,
      threeBet: 0.5429999999999999,
    ), // Michael Addamo
    '0.26_0.2_0.09_6': const PreflopRanges(
      vpip: 0.2849,
      pfr: 0.5650999999999999,
      threeBet: 0.5650999999999999,
    ), // Isaac Haxton
    '0.28_0.2_0.09_6': const PreflopRanges(
      vpip: 0.24939999999999998,
      pfr: 0.5650999999999999,
      threeBet: 0.5650999999999999,
    ), // Brad Owen
    '0.29_0.15_0.05_6': const PreflopRanges(
      vpip: 0.23590000000000003,
      pfr: 0.5699,
      threeBet: 0.5869,
    ), // Jeremy Ausmus
    '0.25_0.18_0.08_6': const PreflopRanges(
      vpip: 0.2866,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Kristen Foxen
    '0.3_0.2_0.1_6': const PreflopRanges(
      vpip: 0.23340000000000002,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Alex Foxen
    '0.35_0.23_0.13_6': const PreflopRanges(
      vpip: 0.1571,
      pfr: 0.5754,
      threeBet: 0.5754,
    ), // Jamie Gold
    '0.24_0.17_0.07_6': const PreflopRanges(
      vpip: 0.29940000000000005,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Lexi Gavin-Mather
    '0.4_0.25_0.13_6': const PreflopRanges(
      vpip: 0.1534,
      pfr: 0.5494,
      threeBet: 0.5494,
    ), // Ethan Yao
    '0.25_0.19_0.09_6': const PreflopRanges(
      vpip: 0.2866,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Garrett Adelstein
    '0.2_0.14_0.04_6': const PreflopRanges(
      vpip: 0.3586,
      pfr: 0.5754,
      threeBet: 0.6194000000000001,
    ), // Phil Hellmuth
    '0.27_0.2_0.12_6': const PreflopRanges(
      vpip: 0.2429,
      pfr: 0.6059999999999999,
      threeBet: 0.6059999999999999,
    ), // Tony Guoga
    '0.29_0.19_0.08_6': const PreflopRanges(
      vpip: 0.24939999999999998,
      pfr: 0.5650999999999999,
      threeBet: 0.5650999999999999,
    ), // Jett Jones
    '0.23_0.17_0.08_6': const PreflopRanges(
      vpip: 0.303,
      pfr: 0.5869,
      threeBet: 0.5869,
    ), // Phil Laak
    '0.24_0.18_0.1_6': const PreflopRanges(
      vpip: 0.2709,
      pfr: 0.5933999999999999,
      threeBet: 0.5933999999999999,
    ), // Maria Ho
    '0.3_0.24_0.12_6': const PreflopRanges(
      vpip: 0.24939999999999998,
      pfr: 0.5437000000000001,
      threeBet: 0.5437000000000001,
    ), // Annette Obrestad
    '0.28_0.22_0.12_6': const PreflopRanges(
      vpip: 0.24939999999999998,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Arash Shahi
    '0.24_0.18_0.08_6': const PreflopRanges(
      vpip: 0.30089999999999995,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Masato Yokosawa
    '0.38_0.26_0.13_6': const PreflopRanges(
      vpip: 0.1823,
      pfr: 0.5393,
      threeBet: 0.5393,
    ), // Shan Srinivasan
    '0.25_0.19_0.11_6': const PreflopRanges(
      vpip: 0.2709,
      pfr: 0.6059999999999999,
      threeBet: 0.6059999999999999,
    ), // Stephen Chidwick
    '0.26_0.2_0.11_6': const PreflopRanges(
      vpip: 0.2497,
      pfr: 0.5869,
      threeBet: 0.5869,
    ), // Fedor Holz
    '0.27_0.2_0.11_6': const PreflopRanges(
      vpip: 0.2497,
      pfr: 0.5869,
      threeBet: 0.5869,
    ), // Justin Bonomo
    '0.27_0.21_0.12_6': const PreflopRanges(
      vpip: 0.2497,
      pfr: 0.5869,
      threeBet: 0.5869,
    ), // Adrian Mateos
    '0.29_0.22_0.13_6': const PreflopRanges(
      vpip: 0.23340000000000002,
      pfr: 0.5869,
      threeBet: 0.5869,
    ), // Bryn Kenney
    '0.25_0.19_0.1_6': const PreflopRanges(
      vpip: 0.2737,
      pfr: 0.5869,
      threeBet: 0.5869,
    ), // Koray Aldemir
    '0.28_0.21_0.12_6': const PreflopRanges(
      vpip: 0.2429,
      pfr: 0.5933999999999999,
      threeBet: 0.5933999999999999,
    ), // Dario Sammartino
    '0.26_0.19_0.1_6': const PreflopRanges(
      vpip: 0.2709,
      pfr: 0.5869,
      threeBet: 0.5869,
    ), // Brian Rast
    '0.3_0.23_0.13_6': const PreflopRanges(
      vpip: 0.23340000000000002,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Doug Polk
    '0.28_0.21_0.11_6': const PreflopRanges(
      vpip: 0.2497,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Paul Sokolov
    '0.29_0.22_0.12_6': const PreflopRanges(
      vpip: 0.2429,
      pfr: 0.5754,
      threeBet: 0.5754,
    ), // Ben Lamb
    '0.3_0.22_0.12_6': const PreflopRanges(
      vpip: 0.23340000000000002,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Carlos Mortensen
    '0.33_0.25_0.14_6': const PreflopRanges(
      vpip: 0.198,
      pfr: 0.5650999999999999,
      threeBet: 0.5650999999999999,
    ), // Vanessa Selbst
    '0.31_0.23_0.13_6': const PreflopRanges(
      vpip: 0.22229999999999997,
      pfr: 0.5754,
      threeBet: 0.5754,
    ), // Patrik Antonius
    '0.32_0.24_0.13_6': const PreflopRanges(
      vpip: 0.2109,
      pfr: 0.5650999999999999,
      threeBet: 0.5650999999999999,
    ), // David Benyamine
    '0.31_0.23_0.12_6': const PreflopRanges(
      vpip: 0.23590000000000003,
      pfr: 0.558,
      threeBet: 0.558,
    ), // Eli Elezra
    '0.34_0.25_0.13_6': const PreflopRanges(
      vpip: 0.198,
      pfr: 0.5494,
      threeBet: 0.5494,
    ), // Qui Nguyen
    '0.3_0.22_0.11_6': const PreflopRanges(
      vpip: 0.2429,
      pfr: 0.5650999999999999,
      threeBet: 0.5650999999999999,
    ), // Doyle Brunson
    '0.27_0.2_0.1_6': const PreflopRanges(
      vpip: 0.2497,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Johnny Chan
    '0.22_0.16_0.08_6': const PreflopRanges(
      vpip: 0.3066,
      pfr: 0.6107,
      threeBet: 0.6107,
    ), // Howard Lederer
    '0.25_0.18_0.1_6': const PreflopRanges(
      vpip: 0.2497,
      pfr: 0.6059999999999999,
      threeBet: 0.6059999999999999,
    ), // Mike Sexton
    '0.33_0.24_0.12_6': const PreflopRanges(
      vpip: 0.22229999999999997,
      pfr: 0.5494,
      threeBet: 0.5494,
    ), // Jennifer Tilly
    '0.18_0.12_0.04_6': const PreflopRanges(
      vpip: 0.3586,
      pfr: 0.6059999999999999,
      threeBet: 0.6194000000000001,
    ), // Allen Kessler
    '0.2_0.14_0.06_6': const PreflopRanges(
      vpip: 0.32799999999999996,
      pfr: 0.6059999999999999,
      threeBet: 0.6059999999999999,
    ), // Jeff Lisandro
    '0.23_0.17_0.09_6': const PreflopRanges(
      vpip: 0.29230000000000006,
      pfr: 0.6059999999999999,
      threeBet: 0.6059999999999999,
    ), // Bing Diao
    '0.32_0.2_0.1_6': const PreflopRanges(
      vpip: 0.198,
      pfr: 0.5754,
      threeBet: 0.5754,
    ), // Paul Phua
    '0.31_0.21_0.11_6': const PreflopRanges(
      vpip: 0.22229999999999997,
      pfr: 0.5754,
      threeBet: 0.5754,
    ), // Elton Tsang
    '0.26_0.2_0.12_6': const PreflopRanges(
      vpip: 0.24939999999999998,
      pfr: 0.6040000000000001,
      threeBet: 0.6040000000000001,
    ), // Seth Davies
    '0.29_0.21_0.12_6': const PreflopRanges(
      vpip: 0.23340000000000002,
      pfr: 0.5880000000000001,
      threeBet: 0.5880000000000001,
    ), // Tan Xuan
    '0.3_0.22_0.13_6': const PreflopRanges(
      vpip: 0.22229999999999997,
      pfr: 0.5880000000000001,
      threeBet: 0.5880000000000001,
    ), // Daniel Cates
    '0.3_0.21_0.11_6': const PreflopRanges(
      vpip: 0.23340000000000002,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Wang Ye
    '0.29_0.21_0.11_6': const PreflopRanges(
      vpip: 0.2429,
      pfr: 0.5754,
      threeBet: 0.5754,
    ), // Xu Liang
    '0.28_0.2_0.11_6': const PreflopRanges(
      vpip: 0.2466,
      pfr: 0.5880000000000001,
      threeBet: 0.5880000000000001,
    ), // Sosia Jiang
    '0.31_0.21_0.1_6': const PreflopRanges(
      vpip: 0.2309,
      pfr: 0.5650999999999999,
      threeBet: 0.5650999999999999,
    ), // Chris Moneymaker
    '0.26_0.19_0.11_6': const PreflopRanges(
      vpip: 0.2497,
      pfr: 0.6059999999999999,
      threeBet: 0.6059999999999999,
    ), // Lucas Jumalon
    '0.34_0.24_0.13_6': const PreflopRanges(
      vpip: 0.198,
      pfr: 0.5650999999999999,
      threeBet: 0.5650999999999999,
    ), // Martin Kabrhel
    '0.27_0.19_0.1_6': const PreflopRanges(
      vpip: 0.2497,
      pfr: 0.5880000000000001,
      threeBet: 0.5880000000000001,
    ), // Andrew Neeme
    '0.32_0.21_0.1_6': const PreflopRanges(
      vpip: 0.2109,
      pfr: 0.5650999999999999,
      threeBet: 0.5650999999999999,
    ), // Ryan DePaulo
    '0.22_0.15_0.06_6': const PreflopRanges(
      vpip: 0.314,
      pfr: 0.5869,
      threeBet: 0.5869,
    ), // Nathan Williams
    '0.32_0.21_0.11_6': const PreflopRanges(
      vpip: 0.2109,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Will Kassouf
    '0.34_0.26_0.14_6': const PreflopRanges(
      vpip: 0.198,
      pfr: 0.5437000000000001,
      threeBet: 0.5437000000000001,
    ), // Tom Dwan
    '0.27_0.19_0.09_6': const PreflopRanges(
      vpip: 0.2497,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Chip Reese
    '0.42_0.3_0.14_6': const PreflopRanges(
      vpip: 0.164,
      pfr: 0.49939999999999996,
      threeBet: 0.49939999999999996,
    ), // Gus Hansen
    '0.38_0.3_0.14_6': const PreflopRanges(
      vpip: 0.22229999999999997,
      pfr: 0.5011,
      threeBet: 0.5011,
    ), // Viktor Blom
    '0.45_0.3_0.12_6': const PreflopRanges(
      vpip: 0.164,
      pfr: 0.4837,
      threeBet: 0.4837,
    ), // Alan Keating
    '0.28_0.19_0.08_6': const PreflopRanges(
      vpip: 0.2709,
      pfr: 0.558,
      threeBet: 0.558,
    ), // Johnny Moss
    '0.21_0.14_0.05_6': const PreflopRanges(
      vpip: 0.32939999999999997,
      pfr: 0.5869,
      threeBet: 0.5869,
    ), // Dan Harrington
    '0.3_0.21_0.09_6': const PreflopRanges(
      vpip: 0.24939999999999998,
      pfr: 0.5494,
      threeBet: 0.5494,
    ), // Lyle Berman
    '0.33_0.25_0.12_6': const PreflopRanges(
      vpip: 0.2251,
      pfr: 0.5393,
      threeBet: 0.5393,
    ), // Layne Flack
    '0.32_0.24_0.11_6': const PreflopRanges(
      vpip: 0.2429,
      pfr: 0.5393,
      threeBet: 0.5393,
    ), // David Ulliott
    '0.29_0.2_0.08_6': const PreflopRanges(
      vpip: 0.2709,
      pfr: 0.5437000000000001,
      threeBet: 0.5437000000000001,
    ), // Chau Giang
    '0.24_0.16_0.06_6': const PreflopRanges(
      vpip: 0.29940000000000005,
      pfr: 0.5754,
      threeBet: 0.5754,
    ), // Robert Varkonyi
    '0.33_0.24_0.1_6': const PreflopRanges(
      vpip: 0.23590000000000003,
      pfr: 0.5294,
      threeBet: 0.5294,
    ), // Jerry Yang
    '0.21_0.15_0.06_6': const PreflopRanges(
      vpip: 0.32799999999999996,
      pfr: 0.5880000000000001,
      threeBet: 0.5880000000000001,
    ), // Hossein Ensan
    '0.25_0.18_0.09_6': const PreflopRanges(
      vpip: 0.2709,
      pfr: 0.5869,
      threeBet: 0.5869,
    ), // Damian Salas
    '0.31_0.24_0.14_6': const PreflopRanges(
      vpip: 0.2251,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Juan Pardo
    '0.33_0.24_0.11_6': const PreflopRanges(
      vpip: 0.2251,
      pfr: 0.5393,
      threeBet: 0.5393,
    ), // Chino Rheem
    '0.28_0.22_0.13_6': const PreflopRanges(
      vpip: 0.2429,
      pfr: 0.5869,
      threeBet: 0.5869,
    ), // Niklas Astedt
    '0.32_0.24_0.14_6': const PreflopRanges(
      vpip: 0.21830000000000002,
      pfr: 0.5699,
      threeBet: 0.5699,
    ), // Wiktor Malinowski
    '0.26_0.18_0.08_6': const PreflopRanges(
      vpip: 0.2737,
      pfr: 0.5754,
      threeBet: 0.5754,
    ), // Adam Friedman
    '0.3_0.21_0.1_6': const PreflopRanges(
      vpip: 0.23590000000000003,
      pfr: 0.5650999999999999,
      threeBet: 0.5650999999999999,
    ), // Joey Ingram
    '0.31_0.22_0.11_6': const PreflopRanges(
      vpip: 0.23340000000000002,
      pfr: 0.5686,
      threeBet: 0.5686,
    ), // Jaman Burton
    '0.29_0.2_0.09_6': const PreflopRanges(
      vpip: 0.24939999999999998,
      pfr: 0.5650999999999999,
      threeBet: 0.5650999999999999,
    ), // Nick Vertucci
    '0.36_0.25_0.11_6': const PreflopRanges(
      vpip: 0.198,
      pfr: 0.5294,
      threeBet: 0.5294,
    ), // Jean-Robert Bellande
  };

  /// Calibrated ranges for [profile], cached by its targets + table size.
  PreflopRanges rangesFor(PlayerProfile profile) {
    final b = profile.strategicBaseline;
    final key =
        '${b.vpipTarget}_${b.pfrTarget}_${b.threeBetFrequency}_$playerCount';
    return _cache[key] ??= calibrate(profile);
  }

  /// Runs the calibration loop and returns the tuned ranges.
  PreflopRanges calibrate(PlayerProfile profile) {
    final b = profile.strategicBaseline;
    final targetVpip = b.vpipTarget;
    final target3 = b.threeBetFrequency;
    // PFR = opens + 3-bets, so the open frequency to aim for is PFR − 3-bet.
    final targetOpen = (b.pfrTarget - target3).clamp(0.0, 1.0);

    // Admitted fractions of all hands for each band, seeded from the targets.
    var qVpip = targetVpip;
    var qOpen = b.pfrTarget;
    var q3 = target3;

    var ranges = _rangesFrom(qVpip, qOpen, q3);
    for (var it = 0; it < iterations; it++) {
      final m = _measure(profile, ranges, seed + it);
      final measuredOpen = (m.pfr - m.threeBet).clamp(0.0, 1.0);

      qVpip = _step(qVpip, targetVpip, m.vpip);
      qOpen = _step(qOpen, targetOpen, measuredOpen);
      q3 = _step(q3, target3, m.threeBet);

      // Keep the bands nested: 3-bet ⊆ open ⊆ VPIP (tighter = smaller fraction).
      if (q3 > qOpen) q3 = qOpen;
      if (qOpen > qVpip) qVpip = qOpen;

      ranges = _rangesFrom(qVpip, qOpen, q3);
    }
    return ranges;
  }

  PreflopRanges _rangesFrom(double qVpip, double qOpen, double q3) =>
      PreflopRanges(
        vpip: PreflopRanges.thresholdForFraction(qVpip),
        pfr: PreflopRanges.thresholdForFraction(qOpen),
        threeBet: PreflopRanges.thresholdForFraction(q3),
      );

  /// One damped proportional step of the admitted fraction toward [target].
  double _step(double q, double target, double measured) {
    if (target <= 0) return 0.0;
    final ratio = measured <= 1e-6 ? 2.0 : (target / measured).clamp(0.5, 2.0);
    return (q * pow(ratio, 0.7)).clamp(0.002, 0.999);
  }

  /// Plays [handsPerIteration] hands with seat 0 running [profile] under
  /// [ranges] against a *reference field* of competent heuristic opponents (the
  /// realistic environment its stats reflect), and returns the hero's measured
  /// preflop frequencies (0–1 fractions). The button rotates, so the hero plays
  /// every position evenly.
  ({double vpip, double pfr, double threeBet}) _measure(
    PlayerProfile profile,
    PreflopRanges ranges,
    int runSeed,
  ) {
    final deckRandom = Random(runSeed);
    final hero = ProfilePolicy(
      profile,
      ranges: ranges,
      random: Random(runSeed * 7 + 1),
    );
    final field = <DecisionPolicy>[
      for (var i = 1; i < playerCount; i++)
        BotStrategy(random: Random(runSeed * 13 + i)),
    ];
    DecisionPolicy policyFor(int seat) => seat == 0 ? hero : field[seat - 1];

    final players = [
      for (var i = 0; i < playerCount; i++)
        Player(id: 'p$i', name: 'p$i', stack: _startingStack),
    ];
    final game = PokerGame(
      players: players,
      deck: Deck(random: deckRandom),
    );

    var hands = 0, vpip = 0, pfr = 0, threeBet = 0;
    for (var h = 0; h < handsPerIteration; h++) {
      for (final p in players) {
        p.stack = _startingStack; // evaluation: top up so no one busts out
      }
      game.startHand();
      if (game.isHandOver) break;

      final heroDealt = players[0].hole.length == 2;
      var heroVpip = false, heroPfr = false, hero3bet = false;
      var priorRaise = false; // any preflop raise so far this hand

      while (!game.isHandOver) {
        final current = game.currentPlayer;
        if (current == null) break;
        final seat = players.indexOf(current);
        final preflop = game.board.isEmpty;
        final action = policyFor(seat).decide(game, current);
        if (preflop) {
          final isRaise =
              action.type == ActionType.bet ||
              action.type == ActionType.raise ||
              action.type == ActionType.allIn;
          if (seat == 0) {
            if (isRaise) {
              heroPfr = true;
              heroVpip = true;
              if (priorRaise) hero3bet = true;
            } else if (action.type == ActionType.call) {
              heroVpip = true;
            }
          }
          if (isRaise) priorRaise = true;
        }
        game.applyAction(action);
      }

      if (heroDealt) {
        hands++;
        if (heroVpip) vpip++;
        if (heroPfr) pfr++;
        if (hero3bet) threeBet++;
      }
    }

    if (hands == 0) return (vpip: 0, pfr: 0, threeBet: 0);
    return (vpip: vpip / hands, pfr: pfr / hands, threeBet: threeBet / hands);
  }
}
