import 'dart:math';

import 'package:flutter/material.dart';
import 'package:monte/core/domain/ai/home_game_profiles.dart';
import 'package:monte/core/domain/ai/player_profile.dart';
import 'package:monte/core/domain/ai/player_profiles.dart';
import 'package:monte/features/tournament/domain/tournament_structure.dart';
import 'package:monte/features/tournament/presentation/tournament_screen.dart';

/// Tournament lobby: pick a structure, size and buy-in, choose which
/// personalities play, and let the rest of the field auto-fill with a mix of
/// reg-like and pro-like players.
class LobbyScreen extends StatefulWidget {
  const LobbyScreen({super.key, this.humanName = 'You'});

  final String humanName;

  @override
  State<LobbyScreen> createState() => _LobbyScreenState();
}

class _LobbyScreenState extends State<LobbyScreen> {
  String _preset = 'turbo';
  int _fieldSize = 9;
  int _buyIn = 100;
  final _selected = <String>{}; // profile ids the owner explicitly added

  static const _presets = ['turbo', 'standard', 'deep', 'circuit', 'wsop'];
  static const _presetLabels = {
    'turbo': 'Turbo',
    'standard': 'Standard',
    'deep': 'Deep',
    'circuit': 'WSOP Circuit',
    'wsop': 'WSOP Main',
  };
  static const _fields = [6, 9, 80, 180, 1000, 8000];
  static const _buyIns = [11, 55, 100, 500, 1000, 10000];

  // Personality pools (each includes the owner-created customs).
  List<PlayerProfile> get _regs => homeGameProfiles;
  List<PlayerProfile> get _pros => builtInProfiles;
  PlayerProfile? _byId(String id) =>
      [..._regs, ..._pros].where((p) => p.id == id).firstOrNull;

  TournamentStructure get _structure => switch (_preset) {
    'standard' => TournamentStructure.standard(clockMode: LevelClockMode.hands),
    'deep' => TournamentStructure.deep(clockMode: LevelClockMode.hands),
    'circuit' => TournamentStructure.wsopCircuit(
      clockMode: LevelClockMode.hands,
    ),
    'wsop' => TournamentStructure.wsopMainEvent(
      clockMode: LevelClockMode.hands,
    ),
    _ => TournamentStructure.turbo(clockMode: LevelClockMode.hands),
  };

  /// Effective entrants: the chosen field size, but grown so every explicitly
  /// selected player fits (they take a seat, the human takes one, the rest fill).
  int get _entrants => max(_fieldSize, _selected.length + 1);
  int get _tableSize => _entrants <= 9 ? _entrants.clamp(2, 9) : 9;

  /// The bot field: the selected personalities (under their real names) plus an
  /// alternating reg/pro mix to complete the seats. Auto-filled seats play a real
  /// personality's style but wear a unique fictitious name, so the field never
  /// shows the same person twice.
  List<PlayerProfile> _buildField() {
    final rng = Random();
    final field = [
      for (final id in _selected) _byId(id),
    ].whereType<PlayerProfile>().toList();
    final botsNeeded = _entrants - 1;
    final used = <String>{widget.humanName, for (final p in field) p.name};
    var i = 0;
    while (field.length < botsNeeded) {
      final pool = (i % 2 == 0) ? _regs : _pros;
      i++;
      final src = pool.isNotEmpty ? pool : (_regs.isNotEmpty ? _regs : _pros);
      if (src.isEmpty) break;
      final profile = src[rng.nextInt(src.length)];
      field.add(profile.renamed(_uniqueName(used, rng), generated: true));
    }
    return field.take(botsNeeded).toList()..shuffle(rng);
  }

  String _uniqueName(Set<String> used, Random rng) {
    for (var attempt = 0; attempt < 1000; attempt++) {
      final name =
          '${_firsts[rng.nextInt(_firsts.length)]} '
          '${_lasts[rng.nextInt(_lasts.length)]}';
      if (used.add(name)) return name;
    }
    // Exhausted the pool (huge field) — suffix a number.
    final base =
        '${_firsts[rng.nextInt(_firsts.length)]} '
        '${_lasts[rng.nextInt(_lasts.length)]}';
    var n = 2;
    while (!used.add('$base $n')) {
      n++;
    }
    return '$base $n';
  }

  @override
  Widget build(BuildContext context) {
    final s = _structure;
    final paidApprox = _entrants <= 9 ? 3 : (_entrants * 0.15).round();
    return Scaffold(
      appBar: AppBar(title: const Text('Tournament lobby')),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _label('Structure'),
            _choice(
              _presets,
              _preset,
              (v) => setState(() => _preset = v),
              (p) => _presetLabels[p]!,
            ),
            const SizedBox(height: 12),
            _label('Field size'),
            _choice(
              _fields,
              _fieldSize,
              (v) => setState(() => _fieldSize = v),
              _fmt,
            ),
            const SizedBox(height: 12),
            _label('Buy-in'),
            _choice(
              _buyIns,
              _buyIn,
              (v) => setState(() => _buyIn = v),
              (b) => '\$${_fmt(b)}',
            ),
            const SizedBox(height: 12),
            Row(
              children: [
                _label('Players'),
                const Spacer(),
                Text(
                  '${_selected.length} added · '
                  '${_entrants - 1 - _selected.length} auto-filled',
                  style: Theme.of(context).textTheme.bodySmall,
                ),
                TextButton(
                  onPressed: () => setState(
                    () => _selected
                      ..clear()
                      ..addAll([
                        for (final p in _regs) p.id,
                        for (final p in _pros) p.id,
                      ]),
                  ),
                  child: const Text('Select all'),
                ),
                if (_selected.isNotEmpty)
                  TextButton(
                    onPressed: () => setState(_selected.clear),
                    child: const Text('Clear'),
                  ),
              ],
            ),
            Expanded(
              child: Card(
                child: ListView(
                  padding: const EdgeInsets.symmetric(vertical: 4),
                  children: [
                    _sectionHeader('Recreational (${_regs.length})'),
                    for (final p in _regs) _playerTile(p),
                    _sectionHeader('Pros (${_pros.length})'),
                    for (final p in _pros) _playerTile(p),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 8),
            Text(
              '${_titleCase(_preset)} · $_entrants runners · '
              '$_tableSize-max · start ${s.startingStack} '
              '(${(s.startingStack / s.levels.first.bigBlind).round()} BB) · '
              'pool \$${_buyIn * _entrants} · top ~$paidApprox paid',
              style: Theme.of(context).textTheme.bodySmall,
            ),
            const SizedBox(height: 8),
            SizedBox(
              width: double.infinity,
              child: FilledButton.icon(
                icon: const Icon(Icons.emoji_events),
                label: const Text('Register & play'),
                onPressed: () => Navigator.of(context).push(
                  MaterialPageRoute(
                    builder: (_) => TournamentScreen(
                      structure: _structure,
                      field: _buildField(),
                      buyIn: _buyIn,
                      tableSize: _tableSize,
                      humanName: widget.humanName,
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _playerTile(PlayerProfile p) {
    final on = _selected.contains(p.id);
    return CheckboxListTile(
      dense: true,
      value: on,
      onChanged: (v) => setState(() {
        if (v ?? false) {
          _selected.add(p.id);
        } else {
          _selected.remove(p.id);
        }
      }),
      title: Text(p.name),
      subtitle: Text(
        p.archetype.replaceAll('_', ' '),
        maxLines: 1,
        overflow: TextOverflow.ellipsis,
      ),
    );
  }

  Widget _sectionHeader(String text) => Padding(
    padding: const EdgeInsets.fromLTRB(16, 8, 16, 4),
    child: Text(
      text,
      style: TextStyle(
        color: Theme.of(context).colorScheme.primary,
        fontWeight: FontWeight.bold,
        fontSize: 12,
      ),
    ),
  );

  Widget _choice<T>(
    List<T> options,
    T selected,
    ValueChanged<T> onSelect,
    String Function(T) label,
  ) => Wrap(
    spacing: 6,
    runSpacing: 4,
    children: [
      for (final o in options)
        ChoiceChip(
          label: Text(label(o)),
          selected: o == selected,
          onSelected: (_) => onSelect(o),
        ),
    ],
  );

  Widget _label(String text) => Padding(
    padding: const EdgeInsets.only(bottom: 6),
    child: Text(text, style: Theme.of(context).textTheme.titleSmall),
  );
}

String _titleCase(String s) =>
    s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);

/// Formats an int with thousands separators (8000 -> "8,000").
String _fmt(int n) {
  final s = n.toString();
  final b = StringBuffer();
  for (var i = 0; i < s.length; i++) {
    if (i > 0 && (s.length - i) % 3 == 0) b.write(',');
    b.write(s[i]);
  }
  return b.toString();
}

const _firsts = [
  // A
  'Aaron',
  'Abel',
  'Abraham',
  'Adam',
  'Adan',
  'Addison',
  'Adriel',
  'Ahmad',
  'Ahmed',
  'Aidan',
  'Aiden',
  'Alan',
  'Albert',
  'Alberto',
  'Alden',
  'Aldo',
  'Alec',
  'Alejandro',
  'Alex',
  'Alexander',
  'Alexis',
  'Alfonso',
  'Alfred',
  'Alfredo',
  'Ali',
  'Alice',
  'Alicia',
  'Allan',
  'Allen',
  'Allison',
  'Alonzo',
  'Alvin',
  'Amanda',
  'Amber',
  'Amelia',
  'Amari',
  'Amir',
  'Amos',
  'Anderson',
  'Andre',
  'Andres',
  'Andrew',
  'Andy',
  'Angel',
  'Angela',
  'Angelo',
  'Anna',
  'Anthony',
  'Antonio',
  'Archie',
  'Ari',
  'Ariel',
  'Armando',
  'Arnold',
  'Aron',
  'Arthur',
  'Arturo',
  'Asa',
  'Asher',
  'Ashton',
  'August', 'Augustus', 'Austin', 'Ava', 'Avery', 'Axel', 'Ayden',

  // B
  'Barrett',
  'Barry',
  'Bart',
  'Beau',
  'Ben',
  'Benjamin',
  'Bennett',
  'Bennie',
  'Benny',
  'Bernard',
  'Bernardo',
  'Bert',
  'Betty',
  'Bill',
  'Billy',
  'Blaine',
  'Blair',
  'Blake',
  'Bo',
  'Bob',
  'Bobby',
  'Booker',
  'Boston',
  'Bowen',
  'Brad',
  'Braden',
  'Bradley',
  'Brady',
  'Brandon',
  'Brantley',
  'Braxton',
  'Brayden',
  'Brenda',
  'Brendan',
  'Brenden',
  'Brendon',
  'Brennan',
  'Brent',
  'Brentley',
  'Brett',
  'Brian',
  'Brice',
  'Brock',
  'Broderick',
  'Brody',
  'Bronson',
  'Brooks',
  'Brooke',
  'Bruce',
  'Bruno',
  'Bryan', 'Bryant', 'Bryce', 'Bryson', 'Byron',

  // C
  'Cade',
  'Caden',
  'Caiden',
  'Cale',
  'Caleb',
  'Calen',
  'Calvin',
  'Cameron',
  'Camden',
  'Camilo',
  'Carl',
  'Carlos',
  'Carla',
  'Carmen',
  'Carol',
  'Caroline',
  'Carson',
  'Carter',
  'Case',
  'Casey',
  'Cash',
  'Cason',
  'Cassandra',
  'Catherine',
  'Cayden',
  'Cesar',
  'Chad',
  'Chance',
  'Chandler',
  'Charles',
  'Charley',
  'Charlie',
  'Charlotte',
  'Chase',
  'Chas',
  'Chloe',
  'Chris',
  'Christian',
  'Christoph',
  'Christopher',
  'Cian',
  'Clarence',
  'Clark',
  'Claude',
  'Clay',
  'Clayton',
  'Clement',
  'Coby',
  'Cody',
  'Colby',
  'Cole',
  'Colin',
  'Collin',
  'Colt',
  'Colten',
  'Colton',
  'Conner',
  'Connor',
  'Conor',
  'Conrad',
  'Cooper',
  'Corey',
  'Corbin',
  'Cory',
  'Courtney',
  'Craig',
  'Crew',
  'Cristian',
  'Cristopher',
  'Cruz',
  'Cullen', 'Curtis', 'Cynthia', 'Cyril', 'Cyrus',

  // D
  'Dakota',
  'Dale',
  'Dallas',
  'Dalton',
  'Damian',
  'Damien',
  'Damon',
  'Dan',
  'Dana',
  'Dane',
  'Dangelo',
  'Daniel',
  'Daniela',
  'Danielle',
  'Danny',
  'Dante',
  'Daren',
  'Darian',
  'Darien',
  'Darin',
  'Darius',
  'Darnell',
  'Darrell',
  'Darren',
  'Darrin',
  'Darryl',
  'Darwin',
  'Dashawn',
  'Dave',
  'David',
  'Davin',
  'Davis',
  'Dawson',
  'Dax',
  'Deacon',
  'Dean',
  'Deandre',
  'Declan',
  'Deion',
  'Denis',
  'Denise',
  'Denny',
  'Denton',
  'Derek',
  'Derick',
  'Derrick',
  'Deshawn',
  'Desmond',
  'Devin',
  'Devon',
  'Dewayne',
  'Dewey',
  'Dexter',
  'Diamond',
  'Diana',
  'Diego',
  'Dillan',
  'Dillon',
  'Dimitri',
  'Dion',
  'Dirk',
  'Dixon',
  'Dominic',
  'Dominick',
  'Don',
  'Donald',
  'Donavon',
  'Donnell',
  'Donnie',
  'Donovan',
  'Dorian',
  'Doyle',
  'Drake',
  'Drew',
  'Duane',
  'Dudley',
  'Duncan',
  'Dustin',
  'Dusty',
  'Dwayne',
  'Dwight', 'Dylan',

  // E
  'Ean',
  'Earl',
  'Eason',
  'Easton',
  'Ebbie',
  'Ed',
  'Eddie',
  'Eddy',
  'Eden',
  'Edgar',
  'Edison',
  'Edmund',
  'Edouard',
  'Edsel',
  'Eduardo',
  'Edward',
  'Edwin',
  'Efraim',
  'Efrain',
  'Elaine',
  'Elam',
  'Elbert',
  'Elden',
  'Eldon',
  'Eli',
  'Elias',
  'Elijah',
  'Elio',
  'Eliot',
  'Eliseo',
  'Elisha',
  'Elizabeth',
  'Ella',
  'Elliot',
  'Elliott',
  'Ellis',
  'Ellison',
  'Elmer',
  'Elmo',
  'Elton',
  'Elvis',
  'Emanuel',
  'Emerson',
  'Emery',
  'Emily',
  'Emilio',
  'Emma',
  'Emmanuel',
  'Emmet',
  'Emmett',
  'Emmitt',
  'Emory',
  'Enoch',
  'Enrique',
  'Enzo',
  'Ephraim',
  'Eric',
  'Erich',
  'Erick',
  'Erik',
  'Erika',
  'Erin',
  'Ernest',
  'Ernesto',
  'Ernie',
  'Ervin',
  'Erwin',
  'Esteban',
  'Ethan',
  'Ethen',
  'Eugene',
  'Eusebio',
  'Evan',
  'Evander',
  'Everett',
  'Ezekiel',
  'Ezequiel',
  'Ezra',

  // F
  'Fabian',
  'Felipe',
  'Felix',
  'Ferdinand',
  'Fermin',
  'Fernando',
  'Fidel',
  'Filiberto',
  'Finn',
  'Finnegan',
  'Fletcher',
  'Floyd',
  'Forest',
  'Forrest',
  'Foster',
  'Francesco',
  'Francis',
  'Francisco',
  'Franco',
  'Frank',
  'Frankie',
  'Franklin',
  'Franklyn',
  'Fred',
  'Freddie',
  'Freddy',
  'Frederic',
  'Frederick',
  'Fredric',
  'Fritz',

  // G
  'Gabe',
  'Gabriel',
  'Gael',
  'Gage',
  'Gaige',
  'Gale',
  'Galen',
  'Garfield',
  'Garret',
  'Garrett',
  'Garrison',
  'Garry',
  'Garth',
  'Gary',
  'Gaston',
  'Gavin',
  'Gene',
  'Geoffrey',
  'George',
  'Gerald',
  'Gerard',
  'Gerardo',
  'German',
  'Gerry',
  'Gideon',
  'Gil',
  'Gilbert',
  'Gilberto',
  'Gino',
  'Giovanni',
  'Giuseppe',
  'Glen',
  'Glenn',
  'Glynn',
  'Godfrey',
  'Gorden',
  'Gordon',
  'Grace',
  'Grady',
  'Graham',
  'Grant',
  'Grayson',
  'Greg',
  'Gregg',
  'Gregorio',
  'Gregory',
  'Grover',
  'Guadalupe',
  'Guillermo',
  'Gunnar',
  'Gunner', 'Gus', 'Gustavo', 'Guy',

  // H
  'Hakeem',
  'Hal',
  'Hale',
  'Halen',
  'Hall',
  'Hamilton',
  'Hampton',
  'Hank',
  'Hans',
  'Harlan',
  'Harley',
  'Harold',
  'Harris',
  'Harrison',
  'Harry',
  'Harvey',
  'Hassan',
  'Hayden',
  'Hayes',
  'Heath',
  'Hector',
  'Hezekiah',
  'Hiram',
  'Hobart',
  'Hogan',
  'Holden',
  'Homer',
  'Horace',
  'Horacio',
  'Hosea',
  'Houston',
  'Howard',
  'Hubert',
  'Hudson',
  'Hugh',
  'Hugo',
  'Humberto',
  'Hunter',
  'Hyman',

  // I
  'Ian',
  'Ibrahim',
  'Ignacio',
  'Ike',
  'Immanuel',
  'Ira',
  'Irvin',
  'Irving',
  'Irwin',
  'Isaac',
  'Isabel',
  'Isaiah',
  'Isaias',
  'Isiah',
  'Isidro',
  'Ismael',
  'Israel',
  'Issac',
  'Ivan',
  'Izaiah',

  // J
  'Jabari',
  'Jace',
  'Jack',
  'Jackson',
  'Jacky',
  'Jacob',
  'Jacoby',
  'Jaden',
  'Jadon',
  'Jaeden',
  'Jagger',
  'Jaheim',
  'Jahmal',
  'Jai',
  'Jaiden',
  'Jaime',
  'Jair',
  'Jake',
  'Jalen',
  'Jamal',
  'Jamar',
  'Jamari',
  'Jamel',
  'James',
  'Jameson',
  'Jamie',
  'Jamir',
  'Jamison',
  'Jane',
  'Janet',
  'Janice',
  'Jared',
  'Jarod',
  'Jarred',
  'Jarrett',
  'Jarrod',
  'Jarvis',
  'Jase',
  'Jasen',
  'Jasiah',
  'Jason',
  'Jasper',
  'Javier',
  'Jax',
  'Jaxon',
  'Jaxson',
  'Jay',
  'Jayce',
  'Jayden',
  'Jaydon',
  'Jaylan',
  'Jaylen',
  'Jaylin',
  'Jaylon',
  'Jayson',
  'Jeb',
  'Jed',
  'Jedediah',
  'Jedidiah',
  'Jeff',
  'Jefferson',
  'Jeffery',
  'Jeffrey',
  'Jeffry',
  'Jerald',
  'Jeramiah',
  'Jeremiah',
  'Jeremy',
  'Jermaine',
  'Jerod',
  'Jerome',
  'Jeromy',
  'Jerrell',
  'Jerrod',
  'Jerry',
  'Jess',
  'Jesse',
  'Jessica',
  'Jessie',
  'Jesus',
  'Jett',
  'Jevon',
  'Jimmy',
  'Joaquin',
  'Jody',
  'Joe',
  'Joel',
  'Joey',
  'Johan',
  'John',
  'Johnathan',
  'Johnathon',
  'Johnie',
  'Johnny',
  'Johnson',
  'Jon',
  'Jonah',
  'Jonas',
  'Jonathan',
  'Jonathon',
  'Jordan',
  'Jordon',
  'Jordy',
  'Jorge',
  'Jose',
  'Josef',
  'Joseph',
  'Josephine',
  'Josh',
  'Joshua',
  'Josiah',
  'Josue',
  'Jovan',
  'Jovani',
  'Jovanny',
  'Jovany',
  'Juan',
  'Judah',
  'Judd',
  'Judge',
  'Judson',
  'Jules',
  'Julian',
  'Juliana',
  'Julien',
  'Julio',
  'Julius',
  'June',
  'Justen',
  'Justice',
  'Justin', 'Justus', 'Juvenal',

  // K
  'Kade',
  'Kaden',
  'Kai',
  'Kaiden',
  'Kaleb',
  'Kalen',
  'Kameron',
  'Kamden',
  'Kane',
  'Kareem',
  'Karl',
  'Karsen',
  'Karson',
  'Karter',
  'Kasey',
  'Kash',
  'Kavan',
  'Kayden',
  'Kayson',
  'Keagan',
  'Keanu',
  'Keaton',
  'Keegan',
  'Keenan',
  'Keith',
  'Kellan',
  'Kellen',
  'Kelley',
  'Kelvin',
  'Ken',
  'Kendall',
  'Kendrick',
  'Keneth',
  'Kenneth',
  'Kennith',
  'Kenny',
  'Kent',
  'Kenton',
  'Kermit',
  'Keshawn',
  'Keven',
  'Kevin',
  'Kian',
  'Kianu',
  'Kiefer',
  'Kieran',
  'Killian',
  'Kim',
  'King',
  'Kingsley',
  'Kingston',
  'Kion',
  'Kip',
  'Kirby',
  'Kirk',
  'Kobe',
  'Koby',
  'Kody',
  'Kole',
  'Kolby',
  'Koleman',
  'Kollen',
  'Kolten',
  'Kolton',
  'Konner',
  'Konnor',
  'Korey',
  'Kory',
  'Kristian',
  'Kristofer',
  'Kristopher',
  'Kurt',
  'Kurtis',
  'Kyan',
  'Kyle',
  'Kylen',
  'Kyler',
  'Kyree',
  'Kyson',

  // L
  'Lamar',
  'Lamont',
  'Lance',
  'Landen',
  'Landon',
  'Lane',
  'Langston',
  'Larry',
  'Lars',
  'Laurence',
  'Lavern',
  'Laverne',
  'Lawerence',
  'Lawrence',
  'Lawson',
  'Layne',
  'Layton',
  'Lazaro',
  'Leander',
  'Lee',
  'Legacy',
  'Leland',
  'Lemuel',
  'Len',
  'Lenard',
  'Lennie',
  'Lenny',
  'Leo',
  'Leon',
  'Leonard',
  'Leonardo',
  'Leonel',
  'Leopoldo',
  'Leroy',
  'Les',
  'Leslie',
  'Lester',
  'Lev',
  'Levi',
  'Levon',
  'Lewis',
  'Liam',
  'Lincoln',
  'Linden',
  'Lindsey',
  'Linus',
  'Lionel',
  'Lloyd',
  'Logan',
  'Lon',
  'London',
  'Lonie',
  'Lonnie',
  'Lonny',
  'Loren',
  'Lorenzo',
  'Loring',
  'Lorne',
  'Lou',
  'Louie',
  'Louis',
  'Lovell',
  'Lowell',
  'Loy',
  'Loyal',
  'Lucas',
  'Luciano',
  'Lucien',
  'Lucio',
  'Lucius',
  'Lukas', 'Luke', 'Luther', 'Lyle', 'Lyman', 'Lyn', 'Lyndon', 'Lynn',

  // M
  'Mac',
  'Mace',
  'Maceo',
  'Mack',
  'Madden',
  'Maddox',
  'Magnus',
  'Maison',
  'Major',
  'Malachi',
  'Malakai',
  'Malcolm',
  'Malik',
  'Manley',
  'Manuel',
  'Marc',
  'Marcel',
  'Marcelo',
  'Marco',
  'Marcos',
  'Marcus',
  'Mariano',
  'Mario',
  'Marion',
  'Mark',
  'Marko',
  'Marlon',
  'Marquis',
  'Marshall',
  'Martin',
  'Marty',
  'Marvin',
  'Mason',
  'Matteo',
  'Matthew',
  'Matthias',
  'Maurice',
  'Mauricio',
  'Maverick',
  'Max',
  'Maxim',
  'Maximilian',
  'Maximiliano',
  'Maximo',
  'Maximus',
  'Maxwell',
  'Mckinley',
  'Mead',
  'Mel',
  'Melvyn',
  'Melvin',
  'Merle',
  'Merlin',
  'Merrill',
  'Mervin',
  'Micah',
  'Michael',
  'Michal',
  'Micheal',
  'Michel',
  'Mick',
  'Mickey',
  'Miguel',
  'Mike',
  'Mikel',
  'Milan',
  'Miles',
  'Miller',
  'Milo',
  'Milton',
  'Misael',
  'Mitchel',
  'Mitchell',
  'Modesto',
  'Mohamed',
  'Mohammad',
  'Mohammed',
  'Moises',
  'Monroe',
  'Monte',
  'Montgomery',
  'Monty',
  'Mordecai',
  'Morgan',
  'Morris',
  'Moses',
  'Moshe',
  'Muhammad',
  'Murdock',
  'Murphy',
  'Murray', 'Myles', 'Myron',

  // N
  'Naeem',
  'Nash',
  'Nasir',
  'Nate',
  'Nathan',
  'Nathanael',
  'Nathanial',
  'Nathaniel',
  'Neal',
  'Ned',
  'Nehemiah',
  'Neil',
  'Nelson',
  'Nestor',
  'Newell',
  'Newt',
  'Newton',
  'Nicholas',
  'Nick',
  'Nickolas',
  'Nico',
  'Nicolas',
  'Nigel',
  'Niko',
  'Nikolai',
  'Nikolas',
  'Nils',
  'Noah',
  'Noe',
  'Noel',
  'Nolan', 'Norbert', 'Normand', 'Norris', 'Norton', 'Norval',

  // O
  'Obadiah',
  'Oberon',
  'Octavio',
  'Odell',
  'Odin',
  'Okey',
  'Olaf',
  'Olen',
  'Olin',
  'Oliver',
  'Ollie',
  'Omar',
  'Omer',
  'Oney',
  'Oral',
  'Oran',
  'Oren',
  'Orie',
  'Orin',
  'Orion',
  'Orlando',
  'Orlo',
  'Orren',
  'Orson',
  'Orval',
  'Orville',
  'Osbaldo',
  'Osborn',
  'Osborne',
  'Oscar',
  'Osvaldo', 'Oswaldo', 'Otho', 'Otis', 'Ottis', 'Otto', 'Owen', 'Ozzie',

  // P
  'Pablo',
  'Palmer',
  'Paris',
  'Parker',
  'Pascal',
  'Pat',
  'Pate',
  'Patricio',
  'Patrick',
  'Paul',
  'Paxton',
  'Payton',
  'Pedro',
  'Pelham',
  'Pembroke',
  'Penn',
  'Peny',
  'Percy',
  'Perley',
  'Perry',
  'Pete',
  'Peter',
  'Peyton',
  'Phelan',
  'Phil',
  'Philip',
  'Phillip',
  'Phineas',
  'Pierce',
  'Pierre',
  'Pinckney',
  'Pleasant',
  'Prentice',
  'Prescott',
  'Preston',
  'Price',
  'Prince',
  'Prosper',
  'Pryor',

  // Q
  'Quentin', 'Quincy', 'Quinn', 'Quintin', 'Quinton',

  // R
  'Rafael',
  'Rafferty',
  'Rahi',
  'Ral',
  'Raleigh',
  'Ralph',
  'Ramiro',
  'Ramon',
  'Ramsay',
  'Ramsey',
  'Randal',
  'Randall',
  'Randell',
  'Randolf',
  'Randolph',
  'Randy',
  'Ransom',
  'Raoul',
  'Raphael',
  'Rashad',
  'Raul',
  'Ray',
  'Rayburn',
  'Rayden',
  'Rayfield',
  'Raymon',
  'Raymond',
  'Raymund',
  'Raymundo',
  'Rayshawn',
  'Reagan',
  'Reece',
  'Reed',
  'Reese',
  'Reggie',
  'Reginal',
  'Reginald',
  'Reid',
  'Reilly',
  'Remington',
  'Remy',
  'Renaldo',
  'Rene',
  'Reuben',
  'Rex',
  'Rey',
  'Reyes',
  'Reynaldo',
  'Rhea',
  'Rhett',
  'Rhys',
  'Ricardo',
  'Rich',
  'Richard',
  'Richie',
  'Richmond',
  'Rick',
  'Rickey',
  'Rickie',
  'Ricky',
  'Rico',
  'Ridge',
  'Riley',
  'Rio',
  'Rion',
  'Ripley',
  'River',
  'Roan',
  'Rob',
  'Robbie',
  'Robby',
  'Robert',
  'Roberto',
  'Robin',
  'Roby',
  'Rocco',
  'Rock',
  'Rocky',
  'Rod',
  'Roderick',
  'Rodger',
  'Rodney',
  'Rodolfo',
  'Rodrick',
  'Rodrigo',
  'Rogelio',
  'Roger',
  'Rohan',
  'Roland',
  'Rolando',
  'Rolf',
  'Rolland',
  'Roman',
  'Romeo',
  'Ron',
  'Ronald',
  'Ronan',
  'Rondell',
  'Ronnie',
  'Ronny',
  'Roosevelt',
  'Rory',
  'Roscoe',
  'Rosendo',
  'Ross',
  'Rowan',
  'Roy',
  'Royal',
  'Royce',
  'Ruben',
  'Rubin',
  'Rudolf',
  'Rudolph',
  'Rudy',
  'Rufus',
  'Rupert',
  'Russ',
  'Russel',
  'Russell',
  'Rusty',
  'Ryan', 'Ryder', 'Ryker', 'Rylan', 'Ryland',

  // S
  'Sage',
  'Sal',
  'Salvador',
  'Salvatore',
  'Sam',
  'Samir',
  'Sammy',
  'Samson',
  'Samuel',
  'Sandy',
  'Sanford',
  'Santiago',
  'Santino',
  'Santos',
  'Saul',
  'Savion',
  'Sawyer',
  'Schuyler',
  'Scot',
  'Scott',
  'Scottie',
  'Scotty',
  'Seamus',
  'Sean',
  'Sebastian',
  'Sebastien',
  'Cedric',
  'Selmer',
  'Seong',
  'Sergio',
  'Seth',
  'Severo',
  'Seward',
  'Shad',
  'Shain',
  'Shamar',
  'Shane',
  'Shannon',
  'Shanon',
  'Shaun',
  'Shawn',
  'Shay',
  'Shea',
  'Shelby',
  'Sheldon',
  'Shelley',
  'Shelton',
  'Sheridan',
  'Sherman',
  'Sherwood',
  'Shiloh',
  'Sid',
  'Sidney',
  'Sigmund',
  'Silas',
  'Silverio',
  'Simeon',
  'Simon',
  'Simp',
  'Simpson',
  'Sinclair',
  'Skylar',
  'Skyler',
  'Slade',
  'Sloan',
  'Smith',
  'Sol',
  'Solomon',
  'Son',
  'Sonny',
  'Soren',
  'Spencer',
  'Spenser',
  'Spurgeon',
  'Stacey',
  'Stacy',
  'Stan',
  'Stanford',
  'Stanislaus',
  'Stanley',
  'Stanton',
  'Starling',
  'Starr',
  'Stefan',
  'Stephan',
  'Stephen',
  'Sterling',
  'Steve',
  'Steven',
  'Stevie',
  'Steward',
  'Stewart',
  'Stokes',
  'Stone',
  'Stoney',
  'Storm',
  'Stuart',
  'Sullivan',
  'Sully',
  'Sumner',
  'Sunny',
  'Sutton',
  'Swen',
  'Sy',
  'Syed',
  'Sylas',
  'Sylvan',
  'Sylvester',
  'Symon',

  // T
  'T-boy',
  'Tab',
  'Tad',
  'Talon',
  'Tameka',
  'Tammie',
  'Tammra',
  'Tanner',
  'Tariq',
  'Tate',
  'Tavaris',
  'Taves',
  'Tavion',
  'Taylor',
  'Teagan',
  'Ted',
  'Teddy',
  'Tegan',
  'Teodoro',
  'Terence',
  'Terrance',
  'Terrell',
  'Terrence',
  'Terry',
  'Thaddeus',
  'Theadore',
  'Thelbert',
  'Theldon',
  'Thelmo',
  'Theodore',
  'Theodoric',
  'Therman',
  'Theron',
  'Thomas',
  'Thor',
  'Thornton',
  'Thurman',
  'Tian',
  'Tice',
  'Tiger',
  'Tilman',
  'Tim',
  'Timmy',
  'Timothy',
  'Titus',
  'Tobias',
  'Toby',
  'Tod',
  'Todd',
  'Tom',
  'Tomas',
  'Tommie',
  'Tommy',
  'Tony',
  'Torey',
  'Torin',
  'Torrance',
  'Torrey',
  'Tory',
  'Trace',
  'Tracey',
  'Tracy',
  'Trae',
  'Travis',
  'Tray',
  'Tre',
  'Trent',
  'Trenton',
  'Trevion',
  'Trevor',
  'Trey',
  'Tripp',
  'Tristan',
  'Tristen',
  'Tristian',
  'Tristin',
  'Triston',
  'Troy',
  'Truman',
  'Tucker',
  'Turner',
  'Ty',
  'Tyan',
  'Tyler',
  'Tylor',
  'Tyree',
  'Tyreek',
  'Tyreese',
  'Tyrek',
  'Tyrell',
  'Tyrese', 'Tyrone', 'Tyshon', 'Tyson',

  // U
  'Ulysses', 'Umar', 'Urban', 'Uriah', 'Uriel', 'Uris', 'Urmas',

  // V
  'Val',
  'Valentin',
  'Valentino',
  'Van',
  'Vance',
  'Vander',
  'Vaughn',
  'Vdale',
  'Veniamin',
  'Verdell',
  'Vern',
  'Vernal',
  'Verner',
  'Vernie',
  'Vernon',
  'Vic',
  'Vicente',
  'Vick',
  'Victor',
  'Vidal',
  'Vince',
  'Vincent',
  'Vincenzo',
  'Vinson',
  'Virgil',
  'Vito',
  'Vivan',
  'Vlad',
  'Vladimer',
  'Vladimir',
  'Von',

  // W
  'Wade',
  'Wael',
  'Walden',
  'Walker',
  'Wallace',
  'Wally',
  'Walter',
  'Walton',
  'Ward',
  'Warren',
  'Wash',
  'Washington',
  'Watson',
  'Waylon',
  'Wayne',
  'Webb',
  'Weber',
  'Welch',
  'Weldon',
  'Wendell',
  'Werner',
  'Wesley',
  'Wesson',
  'Weston',
  'Wetherill',
  'Wharton',
  'Wheeler',
  'Whit',
  'Whitaker',
  'White',
  'Whitfield',
  'Wil',
  'Wilber',
  'Wilbert',
  'Wilbur',
  'Wiley',
  'Wilford',
  'Wilfred',
  'Wilfredo',
  'Wilhelm',
  'Will',
  'Willard',
  'Willem',
  'William',
  'Williams',
  'Willie',
  'Willis',
  'Wilmer',
  'Wilson',
  'Wilton',
  'Winfield',
  'Winfred',
  'Winifred',
  'Winston',
  'Winthrop',
  'Wisdom',
  'Wolfgang',
  'Wood',
  'Woodrow',
  'Woody',
  'Worden', 'Worthy', 'Wright', 'Wyatt', 'Wyman',

  // X
  'Xander',
  'Xavier',
  'Xavion',
  'Xeno',
  'Xenophon',
  'Xerxes',
  'Ximenez',
  'Xylon',

  // Y
  'Yadiel',
  'Yael',
  'Yahia',
  'Yair',
  'Yamil',
  'Yancey',
  'Yancy',
  'Yandell',
  'Yannick',
  'Yarden',
  'Yasin',
  'Yasser',
  'Yehuda',
  'Yeltsin',
  'Yeremy',
  'Yeshua',
  'Yestin',
  'Yiannis',
  'Yoel',
  'Yogi',
  'Yohan',
  'Yohance',
  'Yonatan',
  'Yong',
  'Yoram',
  'York',
  'Yosef',
  'Yoshi',
  'Youssef',
  'Yovan',
  'Yul', 'Yulian', 'Yuma', 'Yuri', 'Yusef', 'Yusuf', 'Yves', 'Yvon',

  // Z
  'Zac',
  'Zach',
  'Zachariah',
  'Zachary',
  'Zachery',
  'Zack',
  'Zackary',
  'Zackery',
  'Zaid',
  'Zaiden',
  'Zain',
  'Zaine',
  'Zak',
  'Zakary',
  'Zakee',
  'Zaki',
  'Zale',
  'Zalman',
  'Zander',
  'Zane',
  'Zavier',
  'Zayd',
  'Zayden',
  'Zayne',
  'Zeb',
  'Zebediah',
  'Zebulon',
  'Zed',
  'Zeki',
  'Zev',
  'Zion', 'Zoltan', 'Zoran', 'Zowie', 'Zubair', 'Zuri',
];

const _lasts = [
  // A
  'Abbott',
  'Acevedo',
  'Acosta',
  'Adams',
  'Adkins',
  'Aguilar',
  'Aguirre',
  'Alexander',
  'Ali',
  'Allen',
  'Allison',
  'Alvarado',
  'Alvarez',
  'Andersen',
  'Anderson',
  'Andrade',
  'Andrews',
  'Anthony',
  'Archer',
  'Arellano',
  'Arias',
  'Armstrong',
  'Arnold',
  'Arroyo',
  'Ashley',
  'Atkins',
  'Atkinson',
  'Austin',
  'Avery',
  'Avila',
  'Ayala', 'Ayers',

  // B
  'Bailey',
  'Baird',
  'Baker',
  'Baldwin',
  'Ball',
  'Ballard',
  'Banks',
  'Barajas',
  'Barber',
  'Barker',
  'Barlow',
  'Barnes',
  'Barnett',
  'Barr',
  'Barrera',
  'Barrett',
  'Barron',
  'Barry',
  'Bartlett',
  'Barton',
  'Bass',
  'Bates',
  'Bauer',
  'Bautista',
  'Baxter',
  'Bean',
  'Beard',
  'Beasley',
  'Beatty',
  'Beck',
  'Becker',
  'Beltran',
  'Bender',
  'Benitez',
  'Benjamin',
  'Bennett',
  'Benson',
  'Bentley',
  'Benton',
  'Berg',
  'Berger',
  'Bernal',
  'Bernard',
  'Berry',
  'Best',
  'Betancourt',
  'Bishop',
  'Black',
  'Blackburn',
  'Blackwell',
  'Blair',
  'Blake',
  'Blanchard',
  'Blanco',
  'Blankenship',
  'Blevins',
  'Boone',
  'Booth',
  'Bowen',
  'Bowers',
  'Bowman',
  'Boyd',
  'Boyer',
  'Boyle',
  'Bradbury',
  'Bradford',
  'Bradley',
  'Bradshaw',
  'Brady',
  'Branch',
  'Brandt',
  'Brantley',
  'Bravo',
  'Brennan',
  'Brewer',
  'Bridges',
  'Briggs',
  'Bright',
  'Brock',
  'Brooks',
  'Brown',
  'Browning',
  'Bruce',
  'Bryan',
  'Bryant',
  'Buchanan',
  'Buck',
  'Buckley',
  'Bullock',
  'Burch',
  'Burgess',
  'Burke',
  'Burnett',
  'Burns',
  'Burris',
  'Burt',
  'Burton',
  'Bush',
  'Butts',
  'Byrd',

  // C
  'Caballero',
  'Cabrera',
  'Calderon',
  'Caldwell',
  'Calhoun',
  'Callahan',
  'Camacho',
  'Cameron',
  'Camp',
  'Campbell',
  'Campos',
  'Cannon',
  'Cantrell',
  'Cantu',
  'Cardenas',
  'Carey',
  'Carlson',
  'Carney',
  'Carpenter',
  'Carr',
  'Carrillo',
  'Carrington',
  'Carroll',
  'Carson',
  'Carter',
  'Cartwright',
  'Carver',
  'Case',
  'Casey',
  'Cash',
  'Castaneda',
  'Castillo',
  'Castro',
  'Cervantes',
  'Chambers',
  'Chan',
  'Chandler',
  'Chaney',
  'Chang',
  'Chapman',
  'Charles',
  'Chase',
  'Chavez',
  'Chen',
  'Cherry',
  'Cisneros',
  'Clark',
  'Clarke',
  'Clay',
  'Clayton',
  'Clements',
  'Clemons',
  'Cline',
  'Cobb',
  'Cochran',
  'Coffey',
  'Cohen',
  'Cole',
  'Coleman',
  'Collier',
  'Collins',
  'Colon',
  'Combs',
  'Compton',
  'Conley',
  'Conner',
  'Conrad',
  'Contreras',
  'Conway',
  'Cook',
  'Cooke',
  'Cooley',
  'Cooper',
  'Copeland',
  'Cordova',
  'Cormier',
  'Corona',
  'Cortez',
  'Costa',
  'Costello',
  'Couch',
  'Cowan',
  'Cox',
  'Craig',
  'Crane',
  'Crawford',
  'Crosby',
  'Cross',
  'Crouch',
  'Cruz',
  'Cuevas', 'Cummings', 'Cunningham', 'Curry', 'Curtis',

  // D
  'Dale',
  'Dalton',
  'Daniel',
  'Daniels',
  'Davenport',
  'David',
  'Davidson',
  'Davies',
  'Davila',
  'Davis',
  'Dawson',
  'Day',
  'Dean',
  'Decker',
  'Dejesus',
  'Delacruz',
  'Delaney',
  'Deleon',
  'Delgado',
  'Dennis',
  'Denton',
  'Diaz',
  'Dickerson',
  'Dickson',
  'Dill',
  'Dillard',
  'Dillon',
  'Dixon',
  'Dodson',
  'Dominguez',
  'Donaldson',
  'Donovan',
  'Dorsey',
  'Dougherty',
  'Douglas',
  'Downs',
  'Doyle',
  'Drake',
  'Dudley',
  'Duffy',
  'Duke',
  'Duncan',
  'Dunlap',
  'Dunn',
  'Duran',
  'Durham',
  'Dutton',
  'Dye',
  'Dyer',

  // E
  'Eaton',
  'Echols',
  'Eckert',
  'Edwards',
  'Egan',
  'Eldridge',
  'Elliott',
  'Ellis',
  'Ellison',
  'Ellsworth',
  'Elmore',
  'Emerson',
  'England',
  'English',
  'Epperson',
  'Erickson',
  'Erwin',
  'Escobar',
  'Escobedo',
  'Espinoza',
  'Esposito', 'Esquivel', 'Estrada', 'Evans', 'Everett',

  // F
  'Farley',
  'Farmer',
  'Farrell',
  'Faulkner',
  'Ferguson',
  'Fernandez',
  'Ferrell',
  'Fields',
  'Figueroa',
  'Finch',
  'Finley',
  'Fischer',
  'Fisher',
  'Fitzgerald',
  'Fitzpatrick',
  'Fleming',
  'Fletcher',
  'Flores',
  'Floyd',
  'Flynn',
  'Foley',
  'Forbes',
  'Ford',
  'Foreman',
  'Foster',
  'Fowler',
  'Fox',
  'Francis',
  'Franco',
  'Frank',
  'Franklin',
  'Frazier',
  'Frederick',
  'Freeman',
  'French',
  'Frey',
  'Friedman',
  'Fritz',
  'Fry',
  'Frye',
  'Fuentes', 'Fuller', 'Fulton',

  // G
  'Gaines',
  'Gallagher',
  'Gallegos',
  'Galloway',
  'Galvan',
  'Gamble',
  'Garcia',
  'Gardner',
  'Garner',
  'Garrett',
  'Garrison',
  'Garza',
  'Gates',
  'Gay',
  'Gentry',
  'George',
  'German',
  'Gibbs',
  'Gibson',
  'Gilbert',
  'Giles',
  'Gill',
  'Gillespie',
  'Gilmore',
  'Glass',
  'Glenn',
  'Glover',
  'Godfrey',
  'Goff',
  'Golden',
  'Goldstein',
  'Gomez',
  'Gonzales',
  'Gonzalez',
  'Good',
  'Goodman',
  'Goodwin',
  'Gordon',
  'Gould',
  'Graham',
  'Grant',
  'Graves',
  'Gray',
  'Green',
  'Greene',
  'Greer',
  'Gregory',
  'Griffin',
  'Griffith',
  'Grimes',
  'Gross', 'Guerrero', 'Guevara', 'Guthrie', 'Gutierrez', 'Guzman',

  // H
  'Haas',
  'Hahn',
  'Haines',
  'Hale',
  'Haley',
  'Hall',
  'Hamilton',
  'Hammond',
  'Hampton',
  'Hancock',
  'Haney',
  'Hansen',
  'Hanson',
  'Hardin',
  'Harding',
  'Hardy',
  'Harmon',
  'Harper',
  'Harrell',
  'Harrington',
  'Harris',
  'Harrison',
  'Hart',
  'Hartman',
  'Harvey',
  'Hatfield',
  'Hawkins',
  'Hayden',
  'Hayes',
  'Haynes',
  'Hays',
  'Head',
  'Heath',
  'Hebert',
  'Hedgepeth',
  'Hein',
  'Heintz',
  'Heinz',
  'Heller',
  'Helms',
  'Henderson',
  'Hendricks',
  'Hendrix',
  'Henley',
  'Henriquez',
  'Henry',
  'Hensley',
  'Henson',
  'Herman',
  'Hernandez',
  'Herrera',
  'Herring',
  'Hess',
  'Hester',
  'Hewitt',
  'Hickman',
  'Hicks',
  'Higgins',
  'Hill',
  'Hilton',
  'Hines',
  'Hinton',
  'Ho',
  'Hobbs',
  'Hobson',
  'Hodge',
  'Hodges',
  'Hoffman',
  'Hogan',
  'Holden',
  'Holder',
  'Holland',
  'Holloway',
  'Holman',
  'Holmes',
  'Holt',
  'Hood',
  'Hoover',
  'Hopkins',
  'Hopper',
  'Horn',
  'Horne',
  'Horton',
  'House',
  'Houston',
  'Howard',
  'Howe',
  'Howell',
  'Hubbard',
  'Huber',
  'Hudson',
  'Huff',
  'Huffman',
  'Hughes',
  'Hull',
  'Humphrey',
  'Humphries',
  'Hunt',
  'Hunter',
  'Hurley',
  'Hurst', 'Hutchinson', 'Hyde',

  // I
  'Ibarra',
  'Ingram',
  'Inman',
  'Irvin',
  'Irvine',
  'Irwin',
  'Isaac',
  'Isaacs',
  'Isbell',
  'Ivey',

  // J
  'Jackson',
  'Jacobs',
  'Jacobson',
  'James',
  'Jamison',
  'Janzen',
  'Jarvis',
  'Jefferson',
  'Jenkins',
  'Jennings',
  'Jensen',
  'Jimenez',
  'Johns',
  'Johnson',
  'Johnston',
  'Jones',
  'Jordan',
  'Jorgensen',
  'Joseph',
  'Joyce',
  'Juarez', 'Judd', 'Julian', 'Justice',

  // K
  'Kaiser',
  'Kaneshiro',
  'Kang',
  'Katz',
  'Kaufman',
  'Kaye',
  'Keane',
  'Kearney',
  'Keaton',
  'Keefer',
  'Keegan',
  'Keel',
  'Keen',
  'Keenan',
  'Keener',
  'Keenan',
  'Keesee',
  'Kehoe',
  'Keim',
  'Keiser',
  'Keith',
  'Kelleher',
  'Keller',
  'Kelley',
  'Kellogg',
  'Kelly',
  'Kemp',
  'Kendall',
  'Kendrick',
  'Kennedy',
  'Kent',
  'Kerr',
  'Key',
  'Khan',
  'Kidd',
  'Kilgore',
  'Kim',
  'Kimball',
  'Kimble',
  'Kimbrough',
  'King',
  'Kinney',
  'Kirby',
  'Kirk',
  'Kirkland',
  'Klein',
  'Kline',
  'Knapp',
  'Knight',
  'Knowles',
  'Knox', 'Koch', 'Kramer', 'Krause', 'Krueger', 'Kruse', 'Kuhn',

  // L
  'Lacey',
  'Lackey',
  'Lacy',
  'Ladd',
  'Lader',
  'Ladner',
  'Lafferty',
  'Lafleur',
  'Lain',
  'Laine',
  'Laird',
  'Lake',
  'Lama',
  'Lamar',
  'Lamb',
  'Lambert',
  'Lancaster',
  'Land',
  'Lander',
  'Landers',
  'Landis',
  'Landon',
  'Landry',
  'Lane',
  'Laney',
  'Lang',
  'Langan',
  'Lange',
  'Langer',
  'Langford',
  'Langston',
  'Lanier',
  'Lankford',
  'Lantz',
  'Lape',
  'Lapointe',
  'Lara',
  'Lard',
  'Large',
  'Larkin',
  'Larsen',
  'Larson',
  'Lash',
  'Lassiter',
  'Latham',
  'Lathrop',
  'Latimer',
  'Latta',
  'Lau',
  'Laub',
  'Lauer',
  'Laughlin',
  'Lauzon',
  'Lavigne',
  'Law',
  'Lawler',
  'Lawhorn',
  'Lawler',
  'Lawless',
  'Lawrence',
  'Lawson',
  'Lay',
  'Layman',
  'Layne',
  'Layton',
  'Le',
  'Lea',
  'Leach',
  'Leahy',
  'Leake',
  'Lear',
  'Leary',
  'Lease',
  'Leatherman',
  'Leaton',
  'Leavitt',
  'Leblanc',
  'Lebo',
  'Ledesma',
  'Ledford',
  'Ledger',
  'Lee',
  'Leech',
  'Leeper',
  'Lees',
  'Leese',
  'Lefebvre',
  'Lefevre',
  'Lefler',
  'Leftwich',

  // M
  'Mace',
  'Macias',
  'Mack',
  'Mackay',
  'Mackenzie',
  'Mackey',
  'Macdonald',
  'Macias',
  'Mack',
  'Madden',
  'Maddox',
  'Madsen',
  'Maestas',
  'Magana',
  'Magee',
  'Magill',
  'Magnuson',
  'Maguire',
  'Mahahan',
  'Mahan',
  'Mahoney',
  'Maier',
  'Main',
  'Major',
  'Majors',
  'Maldonado',
  'Malloy',
  'Malone',
  'Maloney',
  'Mancini',
  'Manley',
  'Mann',
  'Manning',
  'Mansfield',
  'Manzo',
  'Maples',
  'Marble',
  'March',
  'Marino',
  'Marion',
  'Mark',
  'Marks',
  'Marquardt',
  'Marquez',
  'Marquis',
  'Marr',
  'Marrero',
  'Marsh',
  'Marshall',
  'Martin',

  // N
  'Nall',
  'Nance',
  'Napier',
  'Nardi',
  'Nardone',
  'Nash',
  'Nason',
  'Nasser',
  'Nathan',
  'Nation',
  'Nations',
  'Nava',
  'Navarrete',
  'Navarro',
  'Naylor',
  'Neal',
  'Neale',
  'Nealy',
  'Needham',
  'Neel',

  // O
  'Oakes',
  'Oakley',
  'Oates',
  'Oberg',
  'O\'Brien',
  'O\'Connell',
  'O\'Connor',
  'O\'Donnell',
  'Odom',
  'Olea',

  // P
  'Pace',
  'Pacheco',
  'Pack',
  'Packard',
  'Padilla',
  'Pagan',
  'Page',
  'Paige',
  'Paine',
  'Painter',

  // Q
  'Quackenbush',
  'Qualls',
  'Quarles',
  'Quatrone',
  'Quay',
  'Queen',
  'Quezada',
  'Quick',
  'Quigley',
  'Quill',

  // R
  'Raab',
  'Rabe',
  'Raber',
  'Rabideau',
  'Rabin',
  'Rabinowitz',
  'Raby',
  'Race',
  'Racer',
  'Racey',

  // S
  'Saavedra',
  'Sabatino',
  'Saber',
  'Sabin',
  'Sabine',
  'Sacco',
  'Sachs',
  'Sack',
  'Sackett',
  'Sacks',

  // T
  'Taber',
  'Tabor',
  'Tackett',
  'Taff',
  'Taft',
  'Taggart',
  'Taglia',
  'Tague',
  'Tait',
  'Taitano',

  // U
  'Ubank',
  'Uchida',
  'Udell',
  'Uecker',
  'Ugarte',
  'Uhl',
  'Uhlenbeck',
  'Uhlman',
  'Uhrig',
  'Ulbrich',

  // V
  'Vail',
  'Vaillancourt',
  'Valadez',
  'Valdes',
  'Valdez',
  'Valdivia',
  'Valencia',
  'Valentin',
  'Valentine',
  'Valenzuela',

  // W
  'Waddell',
  'Wade',
  'Wadsworth',
  'Wagener',
  'Waggoner',
  'Wagner',
  'Wagoner',
  'Wahl',
  'Wainwright',
  'Waite',

  // X
  'Xanders', 'Xavier', 'Xiao', 'Xiong', 'Xu',

  // Y
  'Yager',
  'Yager',
  'Yagoda',
  'Yahn',
  'Yake',
  'Yamada',
  'Yamamoto',
  'Yamasaki',
  'Yamashita',
  'Yancey',

  // Z
  'Zabel',
  'Zachary',
  'Zacher',
  'Zack',
  'Zager',
  'Zahn',
  'Zahner',
  'Zaidi',
  'Zaiser',
  'Zajac',
];
